# Numpy

In [7]:
# NumPy is a Python library used for working with arrays.
# It also has functions for working in domain of linear algebra, fourier transform, and matrices.
# NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.
# NumPy stands for Numerical Python.

In [8]:
# NumPy (Numerical Python) is a popular Python library used for numerical computing. 
# It provides support for multi-dimensional arrays and mathematical operations, 
# making it much faster and more efficient than Python's built-in lists.

# Why Use NumPy?

In [9]:
# In Python we have lists that serve the purpose of arrays, but they are slow to process.
# NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
# The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
# Arrays are very frequently used in data science, where speed and resources are very important.

In [ ]:
# Faster Computation – NumPy is much faster than Python lists due to vectorization and optimized C-based implementation.
# Efficient Memory Usage – NumPy arrays take up less memory compared to Python lists.
# Convenient Array Operations – Built-in functions for mathematical, statistical, and linear algebra operations.
# Multi-dimensional Support – NumPy supports 1D, 2D, and n-dimensional arrays (ndarrays).
# Used in Data Science & ML – It is the foundation for libraries like Pandas, SciPy, TensorFlow, and Scikit-learn.

In [ ]:
# 1️⃣ Efficiency (Speed & Performance)
# Python’s built-in lists are not optimized for numerical computations because they store elements as individual objects.
# NumPy arrays store data in a contiguous memory block, making operations much faster compared to lists.

# 2️⃣ Convenient Mathematical Operations
# Unlike Python lists, NumPy arrays support vectorized operations, meaning we can perform operations on entire arrays without using loops.
# It supports various mathematical functions like addition, subtraction, multiplication, mean, standard deviation, etc.

# 3️⃣ Memory Optimization
# NumPy arrays require less memory than Python lists because they store elements of the same type in a contiguous memory space.

# 4️⃣ Multidimensional Support
# While Python lists are one-dimensional by default, NumPy provides support for multi-dimensional arrays (e.g., 2D matrices, 3D tensors).

# 5️⃣ Integration with Other Libraries
# NumPy is the foundation for many popular data science and machine learning libraries, such as Pandas, SciPy, Matplotlib, TensorFlow, and Scikit-learn.

# Why is NumPy Faster Than Lists?

In [10]:
# NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.
# This behavior is called locality of reference in computer science.
# This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

# Installing Numpy

In [11]:
!pip install numpy 

In [14]:
# checking the version of the nump
import numpy as np
print(np.__version__)

1.24.3


# Creating Numpy Object

In [2]:
# NumPy is used to work with arrays. The array object in NumPy is called ndarray.
# We can create a NumPy ndarray object by using the array() function.

In [3]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


# array method in numpy

In [5]:
# The numpy.array() method is used to create a NumPy array from lists, tuples, or other array-like structures.

In [6]:
# Syntax
# numpy.array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)

# 1.Creating an Array from a List

In [7]:
# This is the main input to numpy.array(), which can be a list, tuple, NumPy array, or any array-like structure.
import numpy as np
arr = np.array([10,20,30])
print(arr)
print(type(arr))

[10 20 30]
<class 'numpy.ndarray'>


# 2. dtype (Optional)

In [8]:
# Specifies the data type of elements in the array.

arr = np.array([10,20,30,40],dtype=float)
print(arr)
print(arr.dtype)


# Common Data Types
# dtype	Description
# int32	32-bit integer
# int64	64-bit integer
# float32	32-bit floating point
# float64	64-bit floating point (default for floats)
# bool_	Boolean (True/False)
# complex64	Complex number with 32-bit real and imaginary parts


# Note: If dtype is not specified, NumPy infers it from the data.

[10. 20. 30. 40.]
float64


# 3.copy (Optional, Default: True)


In [9]:
# Controls whether NumPy makes a new copy of the input data.

In [10]:
print("---------------Copy True--------------------")
l1 = [10,20,30,40]
arr = np.array(l1,copy=True)
print(l1)
print(arr)

# Here it is avoid copying even if the copy parameter is True.
l1[0] = 100
print(l1)
print(arr)

print('---------------Copy False-------------------')
l2 = [100,300]
arr = np.array(l2,copy=False)
print(arr)
l2[0] = 1000
print(arr)
#  Note: copy=False does not guarantee avoiding a copy. NumPy only avoids copying if possible.

---------------Copy True--------------------
[10, 20, 30, 40]
[10 20 30 40]
[100, 20, 30, 40]
[10 20 30 40]
---------------Copy False-------------------
[100 300]
[100 300]


# 4. order (Optional, Default: 'K')

In [11]:
# Controls how array elements are stored in memory.

In [12]:
arr = np.array([[1,2],[3,4]],order='F')
print(arr)
print(arr.dtype)
print(arr.ndim)
print(arr.flags)

# Value	Memory Layout	Description
# 'C'	Row-major (C-style)	Stores elements row by row (default for NumPy).
# 'F'	Column-major (Fortran-style)	Stores elements column by column (better for Fortran-based computations).
# 'A'	Any (Adaptive to Input)	Keeps the input array's order (if possible, otherwise defaults to 'C').
# 'K'	Keep Memory Layout	Preserves the original memory layout (especially when slicing or copying).

# Why Use 'F'?
# Column-major storage is faster in some numerical computations (e.g., Fortran-based libraries).

[[1 2]
 [3 4]]
int32
2
  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [13]:
# 🔹 1️⃣ 'C' Order (Row-Major Storage)
# 💡 C-style row-major storage:
# 👉 Elements are stored row by row in memory.
# 👉 Faster for row-wise operations.
# 👉 Default format in NumPy.

arr = np.array([[1,2],[3,4]],order='C')
print(arr)
print(arr.flags)
# The C_CONTIGUOUS flag is True, meaning elements are stored row by row.



[[1 2]
 [3 4]]
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [14]:
# 2.F' Order (Column-Major Storage)
# 💡 Fortran-style column-major storage:
# 👉 Elements are stored column by column in memory.
# 👉 Faster for column-wise operations.
# 👉 Useful for Fortran-based libraries (e.g., SciPy, LAPACK).

arr = np.array([[1,2],[3,4]],order='F')
print(arr)
print(arr.flags)

# The F_CONTIGUOUS flag is True, meaning elements are stored column by column.

[[1 2]
 [3 4]]
  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [15]:
# 3️⃣ order='A' (Adaptive to Input)
# "Keep the order of the input array if possible, otherwise use row-major (C) order."
# 👉 If the input array is in C-order (row-major), the output remains C-ordered.
# 👉 If the input array is in F-order (column-major), the output remains F-ordered.
# 👉 If the input is not a NumPy array, it defaults to C-order.


arr_c = np.array([[1,2],[3,4]],order='C')
# Here order a indicate that perfer the original order in which array is created which ic order c 
# so in the flag you see the C_Continguous is True
arr_a = np.array(arr_c,order='A') 
print(arr_a.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [16]:
# 4️⃣ order='K' (Keep Memory Layout)
# 💡 "Preserve the memory layout of the input array as much as possible."
# 👉 If the input is in C-order, it stays C-ordered.
# 👉 If the input is in F-order, it stays F-ordered.
# 👉 If the input is non-contiguous, it preserves the strides (doesn't necessarily become C or F).

In [17]:
arr_f = np.array([[1,2],[3,4]],order='F')
# Here it keeping the order F as the first time when the array is created the order is f
arr_k = np.array(arr_f,order='K')
print(arr_k)
# In the memory layout you see F_Continuous is True
print(arr_k.flags)

[[1 2]
 [3 4]]
  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [18]:
# Key Differences Between order='A' and order='K'
# Feature	order='A' (Adaptive)	order='K' (Keep Layout)
# Preserves Input Order?	✅ Yes, if input is a NumPy array	✅ Yes, but also preserves stride-based layout
# Default for Lists?	C-order (row-major)	C-order (row-major)
# Works with Slices?	Converts to contiguous	Preserves stride-based slicing
# If Input is C-ordered?	Keeps C-order	Keeps C-order
# If Input is F-ordered?	Keeps F-order	Keeps F-order
# If Input is Non-contiguous?	Converts to contiguous	Preserves strided memory


In [19]:
# What Does "Preserves Strided Memory" Mean in order='K' in NumPy?
# In NumPy, strided memory refers to the way elements are stored in memory, especially for non-contiguous arrays.


# What is Strided Memory?
# Strided memory means that array elements are not stored continuously in memory, but instead with gaps between them.


arr = np.arange(10)
print('Original Array',arr)

sliced_arr = arr[::2] 
print("Sliced Array:", sliced_arr)
print("Strides:", sliced_arr.strides)

Original Array [0 1 2 3 4 5 6 7 8 9]
Sliced Array: [0 2 4 6 8]
Strides: (8,)


In [20]:
# What Are Strides?
# Strides represent the number of bytes between consecutive elements.
# The stride value 8 means that NumPy skips 8 bytes in memory when accessing the next element.



# 6. ndmin (Optional, Default: 0)


In [21]:
# Ensures a minimum number of dimensions for the array.
arr = np.array([1,2,3],ndmin=2)
print(arr)

arr = np.array(10,ndmin=1)
print(arr)

arr = np.array(10)
print(arr)

[[1 2 3]]
[10]
10


# Dimension in Arrays

In [22]:
# A dimension in arrays is one level of array depth (nested arrays).

# 1. 0-D Array

In [23]:
# 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.
# A 0D array (zero-dimensional array) is also called a scalar array. 
# It contains only a single value and has no axes (dimensions).

In [24]:
import numpy as np

arr = np.array(41)
print(arr)
print(type(arr))
print(arr.ndim)

41
<class 'numpy.ndarray'>
0


# Why Use a 0D Array?

In [25]:
# Useful for storing a single computed value from NumPy operations.
# Maintains consistency in data structure when working with arrays of different dimensions.
# Can be expanded into higher dimensions using np.expand_dims().

In [26]:
arr_1D = np.expand_dims(arr, axis=0)  # Convert to 1D
print(arr_1D.shape)  

(1,)


In [27]:
arr_2D = np.expand_dims(arr, axis=(0, 1))  # Convert to 2D
print(arr_2D.shape)  

(1, 1)


# Properties of 0D Array

In [28]:
import numpy as np
arr = np.array(10)
print(arr)
print(type(arr))

10
<class 'numpy.ndarray'>


In [29]:
# 1️⃣  ndim – Returns the Number of Dimensions
# Tells how many dimensions (axes) an array has.
# Always returns an integer.
# A scalar (0D array) has ndim = 0, a 1D array has ndim = 1, a 2D array has ndim = 2, and so on.

print(arr.ndim)
# The number of dimensions of a 0D array is always 0.

0


In [30]:
# 2️⃣  shape – Returns the Shape of the Array
# Tells the size (number of elements) along each dimension (axis).
# Always returns a tuple.
# The length of the tuple equals ndim (number of dimensions).
# A 0D array has shape = (), a 1D array has shape = (n,), a 2D array has shape = (rows, columns), etc.

print(arr.shape)

()


In [31]:
# 3️⃣ size – Returns the Total Number of Elements
# Counts the total number of elements in the array.
# A 0D array always has 1 element.

print(arr.size)
# ✔ The size of a 0D array is always 1, since it contains a single value.

1


In [32]:
# 4️⃣dtype – Returns the Data Type of the Array
# Shows the data type of the value stored in the array.
# The data type depends on the type of number provided.
print(arr.dtype)

# ✔ The dtype tells us whether the value is an int, float, etc.

int32


In [33]:
# 5️⃣ itemsize – Returns the Memory Size of One Element (in Bytes)
# Shows how much memory (in bytes) one element occupies.
# The size depends on the data type (dtype).

print(arr.itemsize)
# int32
# ✔ The memory occupied depends on the dtype of the element.

4


In [34]:
# 6️⃣ item() – Extracts the Scalar Value from the Array
# Returns the actual scalar value from the array as a Python data type.

scalar_value = arr.item()
print(scalar_value)
print(type(scalar_value))

# ✔ item() converts a 0D NumPy array into a normal Python scalar.

10
<class 'int'>


In [35]:
# 7️⃣ data – Returns a Pointer to the Memory Address
# Gives a pointer to the location where the array is stored in memory.
loc = arr.data
print("Return the memory location of the array",loc)

Return the memory location of the array <memory at 0x0000016D8BE9CB80>


# 🔹 Modifying a 0D Array

In [38]:
arr = np.array(10)
arr = 100
print(arr)
print(type(arr))

100
<class 'int'>


In [39]:
# Since a 0D array contains a single value, we can change it directly:
arr = np.array(100)
arr[...] = 1000
print(arr)
print(type(arr))
# We use [...] (ellipsis) to modify the single value inside the 0D array.



1000
<class 'numpy.ndarray'>


In [40]:
# What is Ellipsis (...) in NumPy and Why Do We Use It?
# In NumPy, ... (ellipsis) is a special object that represents "as many colons (:) as needed" to select elements across multiple dimensions.
# However, in the case of 0D arrays, it allows us to access and modify the single scalar value stored in the array.

In [41]:
# 📌 General Usage of ... in Higher-Dimensional Arrays
# When working with multi-dimensional arrays, ... helps select slices across multiple dimensions.
arr = np.arange(27).reshape(3,3,3)
print(arr)
# 🔹 This creates a 3x3x3 array.

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [42]:
# If we want to select all elements along the first and third dimensions but pick only the second row, we can use:
print(arr[:,1,:])

[[ 3  4  5]
 [12 13 14]
 [21 22 23]]


In [43]:
# 🔹 Do We Really Need ... for a 0D Array?
# In most cases, you can directly assign a new value to a 0D array without ...:
arr = np.array(10)
arr = 100
print(arr)
print(type(arr))
# 🔹 However, this replaces arr_0d with a regular Python integer!

100
<class 'int'>


In [44]:
# 🔹 If we want to modify the existing NumPy array without losing its properties, we should use ...:
arr = np.array(100)
arr[...] = 10000
print(arr)
print(type(arr))
# ✔ arr_0d[...] = value ensures we modify the array in place instead of converting it to a regular scalar.

10000
<class 'numpy.ndarray'>


# Arithmetic Operations with 0D Arrays in NumPy

In [45]:
# A 0D array (scalar array) in NumPy behaves like a single number. 
# We can perform arithmetic operations on it just like we do with Python scalars, but it remains a NumPy array, keeping its properties.

In [46]:
arr1 = np.array(10)
arr2 = np.array(20)

In [47]:
# Basic Arithmetic Operations
# We can perform arithmetic operations between:

# 1.Two 0D arrays
# 2.A 0D array and a scalar (Python number)

In [49]:
res = arr1 + arr2
print(res)
print(type(res))

30
<class 'numpy.int32'>


In [50]:
res = arr1 - arr2
print(res)
print(type(res))

-10
<class 'numpy.int32'>


In [51]:
res = arr1 * arr2
print(res)
print(type(res))

200
<class 'numpy.int32'>


In [52]:
res = arr1/ arr2
print(res)
print(type(res))

0.5
<class 'numpy.float64'>


In [53]:
res = arr1//arr2
print(res)
print(type(res))

0
<class 'numpy.int32'>


In [54]:
res  =arr1%arr2
print(res)
print(type(res))

10
<class 'numpy.int32'>


In [55]:
res = arr1**arr2
print(res)
print(type(res))

1661992960
<class 'numpy.int32'>


In [58]:
# Arithmetic Operations with Scalar

res =arr1 + 10
print(res)
print(type(res))

20
<class 'numpy.int32'>


In [59]:
res = arr1 -10
print(res)
print(type(res))

0
<class 'numpy.int32'>


In [60]:
res = arr1/10
print(res)
print(type(res))

1.0
<class 'numpy.float64'>


In [61]:
res = arr1%10
print(res)
print(type(res))

0
<class 'numpy.int32'>


In [62]:
res = arr1//10
print(res)
print(type(res))

1
<class 'numpy.int32'>


In [63]:
res = arr1**10
print(res)
print(type(res))

1410065408
<class 'numpy.int32'>


# 🔹 Mixing 0D and Higher-Dimensional Arrays

In [64]:
# We can perform operations between 0D and multi-dimensional arrays, and NumPy will broadcast the scalar value.

In [65]:
arr0 = np.array(10)
arr1 = np.array([10,20,30])
res  = arr0 + arr1
print(res)
# The resultant will be always in the higher dimension from among them.

[20 30 40]


In [67]:
arr0 = np.array(10)
arr2 = np.array([[10,20,30],[20,30,40]])
res = arr0 + arr2
print(res)
print(type(res))

[[20 30 40]
 [30 40 50]]
<class 'numpy.ndarray'>


In [68]:
# why on performing arithmetic operations on 0d array it returns numpy.int32 not numpy.ndarray ?
# When we perform arithmetic operations on a 0D NumPy array, the result is often a NumPy scalar (e.g., numpy.int32, numpy.float64), not a NumPy array (numpy.ndarray).

In [69]:
# 1️⃣ NumPy Converts 0D Arrays to Scalars for Efficiency

# A 0D array (shape ()) contains only one element.
# NumPy optimizes operations on 0D arrays by returning a NumPy scalar (numpy.int32, numpy.float64, etc.) instead of wrapping it back into an array.
# This avoids unnecessary overhead and makes computations faster.

In [70]:
arr0 = np.array(100)
res = arr0 + 1
print(res)
print(type(res))

101
<class 'numpy.int32'>


In [71]:
# 2️⃣ Scalar Promotion: The Data Type is Preserved
# NumPy preserves the data type during operations:

# If the 0D array is int32, the result is numpy.int32.
# If the 0D array is float64, the result is numpy.float64.

In [72]:
arr_0d = np.array(7, dtype=np.float32)
result = arr_0d * 3.5

print(result)        # Output: 24.5
print(type(result))

24.5
<class 'numpy.float64'>


# From Python Built-in Data Structures

In [1]:
# NumPy arrays (numpy.ndarray) can be created from multiple data structures, including Python built-in collections and other external data formats. 
# Below are the main ways to create a NumPy array.

In [3]:
# 1.1 From a Python List
# A Python list is the most common structure used to create NumPy arrays.

import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
# 1.2 From a Tuple
# A tuple can also be converted into a NumPy array.
arr = np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
# 1.3 From a Set
# A set can also be converted into a NumPy array, but since sets are unordered, the output may differ.
s1 = {1,2,3,4,1,2}
res = list(s1)
arr = np.array(res)
print(arr)
print(type(arr))

# ✔ We convert the set to a list first since NumPy does not directly support unordered collections.

[1 2 3 4]
<class 'numpy.ndarray'>


In [6]:
# 1.4 From a Range (range)
# A range object can be directly converted into a NumPy array.
num = range(1,6)
arr = np.array(num)
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>
