# 1D Array in NumPy

In [1]:
# A 1D array (one-dimensional array) in NumPy is a sequence of elements arranged in a single row or single column. 
# It is similar to a Python list but has the advantages of faster computations, efficient memory usage, and built-in vectorized operations..

# An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
# These are the most common and basic arrays.

In [2]:
# Creating a 1D Array in NumPy
# A 1D NumPy array (also called a vector) can be created using np.array().

In [3]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
print(arr1)
# print(type(arr1))
#  The elements are stored linearly in one row.

[1 2 3 4 5]
<class 'numpy.ndarray'>


# Properties of a 1D NumPy Array in Detail

In [5]:
# 1. type() – Check if it's a NumPy Array
# The type() function confirms whether the object is a NumPy array.

arr1 = np.array([10,20,30,40])
print(arr1)
print(type(arr1))

# Output: <class 'numpy.ndarray'>
# This confirms that arr is an instance of numpy.ndarray.

[10 20 30 40]
<class 'numpy.ndarray'>


In [8]:
# 2. ndim – Number of Dimensions
# The .ndim property tells us the number of axes (dimensions) in the array.

arr1 = np.array([10,20,30,40,50])
print(arr1)
print("The Dimension of the array is",arr1.ndim)



# Array Type	Example	ndim Output
# 0D Array	np.array(5)	0
# 1D Array	np.array([1, 2, 3])	1
# 2D Array	np.array([[1, 2], [3, 4]])	2
# 3D Array	np.array([[[1], [2]], [[3], [4]]])	3


[10 20 30 40 50]
The Dimension of the array is 1


In [14]:
# 3. shape – Shape of the Array
# The .shape property returns a tuple representing the size of the array along each dimension.

arr1 = np.array([10,20,30,40])
print(arr1)
print("The shape of the array is 4 bcz there are only 4 element stored row wise",arr1.shape)

#  Output: (4,) → The array has 4 elements in a single row.
#  In a 1D array, the second value is missing because there is only one axis

[10 20 30 40]
The shape of the array is 4 bcz there are only 4 element stored row wise (4,)


In [16]:
# 4. size – Total Number of Elements
# The .size property tells us the total number of elements in the array.

arr1 = np.array([10,20,30,40,50])
print("The total number of elements in array is",arr1.size)

# Output: 5 → There are 5 elements in this array.

# Array Example	Size Output
# np.array([1, 2, 3, 4])	4
# np.array([[1, 2], [3, 4]])	4
# np.array([[1, 2, 3], [4, 5, 6]])	6


The total number of elements in array is 5


In [21]:
# 5. dtype – Data Type of Elements
# The .dtype property shows the data type of the array elements.

arr1 = np.array([10,20,30,40,50],dtype=np.float64)
print(arr1)
print(arr1.dtype)

[10. 20. 30. 40. 50.]
float64


In [25]:
# 6. itemsize – Memory Size of Each Element
# The .itemsize property gives the size (in bytes) of each element.

arr1 = np.array([10,20,30,40,50])
print(arr1)
print("The size occupied by the each element in byptes is ",arr1.itemsize)

print("The total size occupied by the array is",arr1.size*arr1.itemsize)

[10 20 30 40 50]
The size occupied by the each element in byptes is  4
The total size occupied by the array is 20


In [28]:
# 7. nbytes – Total Memory Used by the Array
# The .nbytes property tells us the total memory occupied by the entire array.

arr1 = np.array([10,20,30,40])
print(arr1)
print("The total size occupied by the array is",arr1.nbytes)

# Output: 20 (for int32 array with 5 elements: 5 × 4 bytes = 20 bytes)
# Formula: nbytes = size * itemsize

[10 20 30 40]
The total size occupied by the array is 16


In [29]:
# 8. T – Transpose of the Array
# The .T property transposes the array, but for a 1D array, it remains unchanged.
arr1 = np.array([10,20,30,40,50])
print(arr1.T)

[10 20 30 40 50]


In [31]:
# 9. flat – Iterator Over Elements
# The .flat property provides a flat iterator to loop through elements efficiently.

arr1 = np.array([10,20,30,40])
print(arr1)

print("--------------Using flat---------")
for item in arr1.flat:
    print(item,end=' ')

[10 20 30 40]
--------------Using flat---------
10 20 30 40 

In [32]:
# The .flat property provides a flat iterator that allows us to iterate over all elements of a NumPy array in a single loop, 
# regardless of the array’s shape.

In [33]:
# What is .flat in NumPy?
# It returns an iterator that lets you access array elements one by one.
# It works for both 1D and multi-dimensional arrays.
# Unlike normal iteration, .flat treats the array as a 1D sequence, even if it’s originally 2D or 3D.


In [34]:
# Using .flat with a 1D Array
# For a 1D array, .flat simply iterates over its elements:

for item in arr1.flat:
    print(item,end=' ')

10 20 30 40 

In [38]:
# Using .flat with a 2D Array
# For multi-dimensional arrays, .flat flattens the array and iterates as if it were 1D.

arr2 = np.array([[10,20],[30,40]])
print(arr2)
print(arr2.ndim)

for item in arr2.flat:
    print(item,end=' ')

[[10 20]
 [30 40]]
2
10 20 30 40 

In [40]:
# Using .flat with a 3D Array
# If we have a 3D array, .flat still iterates over each element one by one.

arr3 = np.array([[[10,20,30],[40,50,60],[70,80,90]]])
print(arr3)
print(arr3.ndim)

for item in arr3.flat:
    print(item,end=' ')

[[[10 20 30]
  [40 50 60]
  [70 80 90]]]
3
10 20 30 40 50 60 70 80 90 

In [42]:
# 10. tolist() – Convert to a Python List
# The .tolist() method converts the NumPy array to a Python list.

arr1 = np.array([10,20,30,40])
print(arr1)
l1 = arr1.tolist()
print(l1)

[10 20 30 40]
[10, 20, 30, 40]


# All Methods of a 1D NumPy

In [2]:
# 1. astype() – Convert to a Different Data Type
# This method allows you to change the data type (dtype) of an array.

import numpy as np

arr1 = np.array([10,20,30])
print(arr1)
print(arr1.dtype)

narr1 = arr1.astype(float)
print(narr1)
print(narr1.dtype)


[10 20 30]
int32
[10. 20. 30.]
float64


In [3]:
# 2. copy() – Create a Copy of the Array
# This method creates an independent copy of the array.

arr1 = np.array([10,20,30,40])
copy_arr1 = arr1.copy()

print("Changing the copy array")
copy_arr1[0] = 1000
print(copy_arr1)
print(arr1)


# Why use copy()? Because modifying a view of an array changes the original, but modifying a copy does not.

Changing the copy array
[1000   20   30   40]
[10 20 30 40]


In [5]:
# 3. view() – Create a View of the Array
# Unlike copy(), a view is linked to the original array.

arr1 = np.array([10,20,30,40,50])
view_arr1 = arr1.view()

print("On Changing the view array changes will be reflected into the original array")
view_arr1[0] = 10000
print("After changing view array",view_arr1)
print("After changing original array",arr1)


On Changing the view array changes will be reflected into the original array
After changing view array [10000    20    30    40    50]
After changing original array [10000    20    30    40    50]


In [14]:
# 4. reshape() – Change the Shape of the Array
# A 1D array can be reshaped into multi-dimensional arrays.

arr1 =  np.array([10,20,30,40])
# Here the first parameter is no. of rows  and second parameter is no of columns.
reshaped_array1 = arr1.reshape(4,1)
print("Original Array",arr1)
print("Reshaped Array",reshaped_array1)
print(type(reshaped_array1))
print()

print("Reshaped into 2D array")
reshaped_array2 = arr1.reshape(2,2)
print("Reshaped Array",reshaped_array2)
print(reshaped_array2.ndim)

Original Array [10 20 30 40]
Reshaped Array [[10]
 [20]
 [30]
 [40]]
<class 'numpy.ndarray'>

Reshaped into 2D array
Reshaped Array [[10 20]
 [30 40]]
2


In [22]:
# 5. ravel() – Flatten a Multi-Dimensional Array into 1D.
# This method is useful when dealing with multi-dimensional arrays.

# Here it return 1d array which the view of the multidimensional array.
# On changing the 1d array the changes will be reflected into the original multidimensional array.

arr2d = np.array([[10,20,30],[40,50,60]])
print("The 2D array",arr2d)
print()

print("Getting the 1D from the MultiDimensional Array")
arr1d = arr2d.ravel()
print("The 1d Array from multidimensional array",arr1d)
print("The multidimensional array",arr2d)
print()

print("On changing the 0 index of the 1d array the changes will be reflected into the multidimensional array")
print("0th index is changed from 10 to 1000")
arr1d[0] = 1000
print(arr1d)
print(arr2d)
print()


arr1d[5] = 6000
print(arr1d)
print(arr2d)
# Use when: You need to convert multi-dimensional arrays to 1D format.

The 2D array [[10 20 30]
 [40 50 60]]

Getting the 1D from the MultiDimensional Array
The 1d Array from multidimensional array [10 20 30 40 50 60]
The multidimensional array [[10 20 30]
 [40 50 60]]

On changing the 0 index of the 1d array the changes will be reflected into the multidimensional array
0th index is changed from 10 to 1000
[1000   20   30   40   50   60]
[[1000   20   30]
 [  40   50   60]]

[1000   20   30   40   50 6000]
[[1000   20   30]
 [  40   50 6000]]


In [27]:
# 6. flatten() – Convert Multi-Dimensional Array to 1D
# Similar to ravel(), but creates a copy instead of a view.
# It return the 1d on changing the 1d array the changes will not be reflected bcz it return the copy of the array not the view.

print("Multidimensional Array")
arr2d = np.array([[10,20,30],[40,50,60]])
print(arr2d)

print("1D array from the MultiDimensional Array")
arr1d = arr2d.flatten()
print(arr1d)




Multidimensional Array
[[10 20 30]
 [40 50 60]]
1D array from the MultiDimensional Array
[10 20 30 40 50 60]


In [32]:
# 7. transpose() or T – Transpose the Array
# For a 1D array, it remains unchanged, but it is useful for 2D+ arrays.

arr1d = np.array([10,20,30,40])
print(arr1d)

arr2d = arr1d.reshape(4,1)
print(arr2d)
print(arr2d.ndim)
print("Transposing the 2d",arr2d.T,arr2d.ndim)

[10 20 30 40]
[[10]
 [20]
 [30]
 [40]]
2
Transposing the 2d [[10 20 30 40]] 2


In [33]:
# 8. max() and min() – Find Maximum and Minimum Value
# Return the maximum and minimum value from the array.

arr1 = np.array([10,20,30,40,50])
print("The maximum value from the array is",arr1.max())
print("The minimum value from the array is",arr1.min())

# Use when: You need to find the largest or smallest element.

The maximum value from the array is 50
The minimum value from the array is 10


In [34]:
# 9. sum() – Calculate Sum of All Elements
# Return the sum of all the elements

arr1 = np.array([10,20,30,40,50])
print(arr1)
print("The sum of all the elements of the array is",arr1.sum())

# Use when: You need to compute the sum of all elements.

[10 20 30 40 50]
The sum of all the elements of the array is 150


In [35]:
# 10. mean() – Find the Average (Mean) Value
# Return the average of the array.

arr1 = np.array([10,20,30,40,50])
print("The mean of the array is",arr1.mean())


The mean of the array is 30.0


In [38]:
# 11. std() and var() – Standard Deviation and Variance

arr1 = np.array([10,20,30,40,50])
print("The standard deviation is",arr1.std())
print("The variance is",arr1.var())

# Use when: You need to measure the spread of data.

The standard deviation is 14.142135623730951
The variance is 200.0


In [41]:
# 12. argmax() and argmin() – Find Indices of Max/Min Values
# Return the index of the array that contains minimum and maximum value.

arr1d = np.array([10,20,30,40,50])
print("The index which contains minimum value is",arr1d.argmin())
print("The index which contains maximum value is",arr1d.argmax())

# Use case: When you need positions instead of values.

The index which contains minimum value is 0
The index which contains maximum value is 4


In [47]:
# 13. sort() – Sort the Array
# It sort the original array.
# Bydefault in ascending order.

arr1d = np.array([3,1,4,5,1,2])
arr1d.sort()
print(arr1d)

[1 1 2 3 4 5]


In [ ]:
# The sort() method in NumPy is used to sort elements in a NumPy array in ascending order by default. 
# It works with 1D, 2D, and multi-dimensional arrays, and it provides options for sorting along different axes.

# Basic Syntax
# numpy.sort(array, axis=-1, kind='quicksort', order=None)

# Parameter	Description
# 1.array	The NumPy array to be sorted
# 2.axis	Specifies the axis along which sorting is performed (default is -1, meaning the last axis)
# 3.kind	The sorting algorithm ('quicksort', 'mergesort', 'heapsort', 'stable')
# 4.order	Used for structured arrays (not needed for normal arrays)


In [51]:
# Sorting a 1D NumPy Array
# sorting the 1d array in ascending order which is default.

arr1d = np.array([4,1,3,1,4,6,7,9,2])
arr1d.sort()
print(arr1d)


[1 1 2 3 4 4 6 7 9]


In [54]:
# Sorting a 1D NumPy Array in Descending Order
arr1d = np.array([1,2,3,4,5])
arr1d = np.sort(arr1d)[::-1]
print(arr1d)

[5 4 3 2 1]


In [56]:
# Sorting a 2D NumPy Array
# For multi-dimensional arrays, sorting is done along axes.

# Sorting Along Rows (axis=1)

arr2d = np.array([[30,20,10],[60,50,40]])
arr2d.sort(axis=1)
# Here the sorting is performed row-wise.
print(arr2d)

[[10 20 30]
 [40 50 60]]


In [59]:
# Sorting Along Column (axis=0)

arr2d = np.array([[30,40,50],[10,20,30]])
arr2d.sort(axis=0)
# Here the sorting is performed column-wise.
print(arr2d)

[[10 20 30]
 [30 40 50]]


In [60]:
# Sorting with Different Sorting Algorithms (kind Parameter)
# NumPy provides four sorting algorithms:

# Algorithm	Description
# 'quicksort'	Default, fast but unstable
# 'mergesort'	Stable (preserves order of equal elements)
# 'heapsort'	Slower but memory efficient
# 'stable'	Best for structured data, keeps order of duplicates


arr1d = np.array([3, 1, 4, 1, 5, 9, 2])
print(np.sort(arr1d,kind='quicksort') # default 
print(np.sort(arr1d,kind='mergesort')) #stable sort
print(np.sort(arr1d,kind='heapsort')) # memory efficient

[1 1 2 3 4 5 9]
[1 1 2 3 4 5 9]
[1 1 2 3 4 5 9]


In [65]:
# Sorting a Structured Array (order Parameter)
# If an array contains named fields, we can sort by a specific field.

dtype = [('name','S10'),('age','int')]
arr1d = np.array([('Alice', 25),('Bob', 22),('Charlie', 30)],dtype=dtype)
arr1d.sort(order='age')
print(arr1d)

# The names are displayed as byte strings (b'Bob') because of the 'S10' dtype.

[(b'Bob', 22) (b'Alice', 25) (b'Charlie', 30)]


In [66]:
# Key Differences Between S10 and U10
# Data Type	Storage Type	Printed Output	Supports Unicode?
# 'S10'	Fixed-size bytes	b'Alice'	❌ No
# 'U10'	Unicode (UTF-32)	'Alice'	✅ Yes

# When to Use S10 vs. U10?
# Use 'S10' (bytes) when working with raw binary data or when size constraints are strict.
# Use 'U10' (Unicode) for normal text handling and human-readable output.

In [57]:
# 14. concatenate() – Combine Two Arrays
# Return the new array which contains all the elements of both the arrays.

arr1d = np.array([1,2,3,4])
arr2d = np.array([5,6,7,8])
arr3d = np.concatenate((arr1d,arr2d))
print(arr3d)

[1 2 3 4 5 6 7 8]


In [67]:
# The concatenate() function in NumPy is used to join two or more arrays along a specified axis.

# Syntax
# numpy.concatenate((array1, array2, ...), axis=0)

# Parameter	Description
# array1, array2, ...	The arrays to be concatenated (must have the same shape along the concatenation axis)
# axis	The axis along which to concatenate (default is 0)

In [68]:
# Concatenating 1D Array

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8])

arr3 = np.concatenate((arr1,arr2))
print(arr3)

[1 2 3 4 5 6 7 8]


In [71]:
# Concatenating 2D Arrays
# By default, axis=0 (rows), but we can also use axis=1 (columns).

arr1 = np.array([[10,20],[30,40]])
arr2 = np.array([[50,60],[70,80]])

arr3 = np.concatenate((arr1,arr2),axis=0)
print(arr3)

[[10 20]
 [30 40]
 [50 60]
 [70 80]]


In [72]:
# colum-wise concatenation

arr1 = np.array([[10,20],[30,40]])
arr2 = np.array([[50,60],[70,80]])

arr3 = np.concatenate((arr1,arr2),axis=1)
print(arr3)

[[10 20 50 60]
 [30 40 70 80]]


In [75]:
# 15. unique() – Find Unique Elements
# Return the array containing the unique elements.
# This method is called with the numpy not with the array.
# bcz array has no attribute or method like unique.

arr1d = np.array([1,1,2,2,3,3,4,5])
uni_arr1d = np.unique(arr1d)
print(uni_arr1d)

# Use case: Removing duplicates.

[1 2 3 4 5]


In [76]:
# The np.unique() function is used to find unique elements in an array. 
# It removes duplicate values and returns a sorted array of unique elements.

# Syntax
# numpy.unique(array, return_index=False, return_counts=False)

# Parameter	Description
# array	Input array from which unique elements are extracted
# return_index	If True, returns the indices of unique elements in the original array
# return_counts	If True, returns the count of each unique element

arr1d = np.array([1,2,1,3,1,4,2,4,5])
new_arr,indices,count = np.unique(arr1d,return_index=True,return_counts=True)
print("The unique elements of the array is",new_arr)
print("The unique indices from the array is",indices)
print("The count of the unique elements is",count)

# return_index=True: Returns the index of the first occurrence of each unique value.
# return_counts=True: Returns how many times each unique element appears.

The unique elements of the array is [1 2 3 4 5]
The unique indices from the array is [0 1 3 5 8]
The count of the unique elements is [3 2 1 2 1]


In [87]:
# 16. where() – Find Elements That Match a Condition
# The np.where() function is used to find the indices of elements in an array that satisfy a given condition.

# Syntax
# numpy.where(condition, [x, y])

# Parameter	Description
# condition	A boolean condition to filter elements
# x, y (optional)	If provided, replaces True values with x and False values with y

#  The output is a tuple containing an array of matching indices.

arr1d = np.array([10,20,30,40,50])
idx = np.where(arr1d>20)
print("The indexes whose value is greater than the condition written in where is",idx,type(idx))

# Use case: Filtering elements dynamically.

The indexes whose value is greater than the condition written in where is (array([2, 3, 4], dtype=int64),) <class 'tuple'>


In [86]:
# Here it repalces the true values with 1000 and false values with 0. 
arr1d = np.array([10,20,30,40,50])
idx = np.where(arr1d>20,1000,0)
print(idx)
print(type(idx))

[   0    0 1000 1000 1000]
<class 'numpy.ndarray'>


In [89]:
# 17. clip() – Limit Values to a Range
# The clip() method in NumPy is used to limit (restrict) values in an array within a specified range.
# If a value is less than the minimum, it is set to the minimum.
# If a value is greater than the maximum, it is set to the maximum.

arr1d = np.array([1,2,3,4,5,6,7,8,9,10])
clip_arr = arr1d.clip(min=2,max=4)
print(clip_arr)

# Use case: Capping values to avoid extreme values.

# Use Case: Avoiding Extreme Values
# Clipping is useful in scenarios like:

# Image Processing: Limiting pixel values between 0-255 to prevent overflow.
# Machine Learning: Preventing extreme outliers in training data.
# Signal Processing: Keeping values within a meaningful range.

[2 2 3 4 4 4 4 4 4 4]


In [91]:
# 18. all() and any() – Boolean Checks

# The all() and any() methods in NumPy are boolean functions that check whether all or some elements in an array are True.

# Syntax
# numpy.all(array, axis=None)
# numpy.any(array, axis=None)

# Method	Description
# all()	Returns True if all elements are True; otherwise, False
# any()	Returns True if at least one element is True

arr1d = np.array([1,2,3,1,0])
new_arr = arr1d.all()
new_arr1 = arr1d.any()
print("Here it return false bcz 0 is treated as the false which means it doesn't contains all the true values",new_arr)
print("Here it returns true bcz the array needs to aleast one true which is present that's why it return true",new_arr1)

Here it return false bcz 0 is treated as the false which means it doesn't contains all the true values False
Here it returns true bcz the array needs to aleast one true which is present that's why it return true True


In [92]:
# Using axis Parameter
# When working with multi-dimensional arrays, we can use axis to check along rows or columns.

arr2d = np.array([[True,True,False],[True,True,True]])
new_row = arr2d.all(axis=0)
new_col = arr2d.all(axis=1)
print(new_row)
print(new_col)


[ True  True False]
[False  True]


In [ ]:
# 19.np.cumsum() and np.cumprod() – Cumulative Sum & Product in NumPy
# Both np.cumsum() and np.cumprod() perform cumulative operations on arrays:

# cumsum() → Returns the cumulative sum of elements.
# cumprod() → Returns the cumulative product of elements.
# These methods are useful in financial analysis, data processing, probability calculations, and signal processing.

In [38]:
# i. np.cumsum() – Cumulative Sum
# cumsum() computes the running total of an array’s elements

# Syntax:
# np.cumsum(array, axis=None, dtype=None, out=None)

# Parameters:
# array → The input array.
# axis → Specifies the axis to compute the cumulative sum (ignored for 1D).
# dtype → Specifies the data type of the output.
# out → A pre-allocated output array (optional).

arr1 = np.array([1,2,3,4,5,6])
print(arr1)

print(arr1.cumsum())
print(type(arr1.cumsum()))

[1 2 3 4 5 6]
[ 1  3  6 10 15 21]
<class 'numpy.ndarray'>


In [40]:
# 2. np.cumprod() – Cumulative Product
# cumprod() calculates the running product of an array’s elements.

# Syntax:
# np.cumprod(array, axis=None, dtype=None, out=None)

# Parameters:
# array → The input array.
# axis → The axis along which to compute (ignored for 1D).
# dtype → Specifies the data type of the output.
# out → A pre-allocated output array (optional).
# use the already created array but the array we are using must have same number of element as the original array.

arr1 = np.array([1,2,3,4,5])
print(arr1)

print(arr1.cumprod())
print(type(arr1.cumprod()))

[1 2 3 4 5]
[  1   2   6  24 120]
<class 'numpy.ndarray'>


# Indexing and Slicing in a 1D NumPy Array

In [41]:
# Indexing and slicing in NumPy work similarly to Python lists but with more powerful features. 
# They allow you to access and modify elements in an array efficiently.

In [42]:
# Indexing in a 1D NumPy Array

# Indexing refers to selecting a specific element from the array using its position (index number).
# In NumPy, indexing starts from 0 (zero-based indexing).


import numpy as np

arr1 = np.array([10,20,30,40,50])
print(arr1)
print(type(arr1))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [43]:
# Positive Indexing
# Which starts from the 0 upto the length of the (1D array - 1).

print(arr1[0])
print(arr1[1])
print(arr1[2])

10
20
30


In [44]:
# Negative Indexing 
# This starts from the -1 to the end of the array and decrease upto the first element of the array.
# You can also use negative indices to access elements from the end.

print(arr1[-1])
print(arr1[-2])
print(arr1[-3])

50
40
30


In [45]:
# Slicing in a 1D NumPy Array

# Slicing allows us to extract a portion (subarray) of elements from the array.
# On Slicing the ndarray array we got the ndarray.

# Basic Syntax
# array[start:stop:step]

# Parameter	Meaning
# start	Starting index (included)
# stop	Stopping index (excluded)
# step	Step size (default is 1)

In [46]:
arr1 = np.array([10,20,30,40,50])
print(arr1)

[10 20 30 40 50]


In [47]:
print(arr1[0:])

[10 20 30 40 50]


In [48]:
print(arr1[:len(arr1)])

[10 20 30 40 50]


In [49]:
print(arr1[:])

[10 20 30 40 50]


In [50]:
print(arr1[1:4])
print(type(arr1[1:4]))

[20 30 40]
<class 'numpy.ndarray'>


In [51]:
# reverse of the ndarray
print(arr1[::-1])

[50 40 30 20 10]


In [52]:
print(arr1[::2])

[10 30 50]


In [53]:
print(arr1[-1:-3:-1])

[50 40]


# Modifying Elements Using Indexing and Slicing

In [54]:
# You can modify elements directly using indexing and slicing.

arr1 = np.array([10,20,30,40,50])
print(arr1)

[10 20 30 40 50]


In [55]:
# Modifying the 0th index of the array
arr1[0] = 1000
# After modifying the 0th index the changes will be reflected into the original array.
print(arr1)

[1000   20   30   40   50]


In [56]:
# Modifying the sequence of values.
arr1[2:4] = [3000,4000]
print(arr1)

[1000   20 3000 4000   50]


In [57]:
# Slicing and indexing are essential in NumPy, and when combined with conditional filtering, they provide powerful ways to manipulate and extract data. 
# Let’s go through various advanced slicing techniques step by step.

# 1. Boolean Indexing: Filtering Elements Using Conditions

In [58]:
#  Selecting Elements Greater Than a Value

arr1 = np.array([10,20,30,40,50])
print(arr1)

arr2 = arr1[arr1>30]
print(arr1)
print(arr2)

# Flow of Execution
# Step	Operation	Result
# 1	Create arr = [10, 20, 30, 40, 50]	[10, 20, 30, 40, 50]
# 2	Apply arr > 25	[False, False, True, True, True]
# 3	NumPy extracts only True values	[30, 40, 50]
# 4	Print result	[30 40 50]

[10 20 30 40 50]
[10 20 30 40 50]
[40 50]


# 2. Filtering Even Numbers

In [59]:
# We can use modulus operator (%) to extract even numbers.

arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr1)

even_arr = arr1[arr1%2==0]
print(even_arr)

# Flow of Execution
# Step	Operation	Result
# 1	Create arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]	[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
# 2	Apply arr % 2 == 0	[False, True, False, True, False, True, False, True, False, True]
# 3	NumPy extracts only True values	[2, 4, 6, 8, 10]
# 4	Print result	[2 4 6 8 10]

[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10]


# 3. Filtering Values Within a Range

In [60]:
# We can use multiple conditions using & (AND) and | (OR).

arr1 = np.array([5,10,15,20,25,30,35])
print(arr1)

range_arr = arr1[((arr1>=10) &(arr1<=25))]
print(range_arr)


# Flow of Execution
# Step	Operation	Result
# 1	Create arr = [5, 10, 15, 20, 25, 30, 35]	[5, 10, 15, 20, 25, 30, 35]
# 2	Apply (arr >= 10) & (arr <= 30)	[False, True, True, True, True, True, False]
# 3	NumPy extracts only True values	[10, 15, 20, 25, 30]
# 4	Print result	[10 15 20 25 30]

[ 5 10 15 20 25 30 35]
[10 15 20 25]


# 4. Replacing Values Based on Conditions

In [61]:
# Instead of just filtering, we can modify elements using conditional indexing.

arr1 = np.array([10,20,30,40,50])
print(arr1)

arr1[arr1>20] = 100
print(arr1)

# Flow of Execution
# Step	Operation	Result
# 1	Create arr = [1, 2, 3, 4, 5, 6]	[1, 2, 3, 4, 5, 6]
# 2	Apply arr > 3	[False, False, False, True, True, True]
# 3	Replace True values with 99	[1, 2, 3, 99, 99, 99]
# 4	Print result	[1 2 3 99 99 99]

[10 20 30 40 50]
[ 10  20 100 100 100]


# 5. Extracting Odd-Indexed Elements Using Slicing


In [63]:
# We can extract elements at odd indices using slicing.

arr1 = np.array([10,20,30,40,50])
print(arr1)

odd_idx_arr = arr1[1::2]
print(odd_idx_arr)

[10 20 30 40 50]
[20 40]
