# 2D Array in NumPy (Two-Dimensional Array)

In [1]:
# A 2D array (two-dimensional array) in NumPy is an array that has rows and columns, 
# making it similar to a matrix or a table.

In [2]:
# 🔹 Key Features of a 2D NumPy Array:
# ✔ Has two axes (dimensions) → axis 0 (rows) and axis 1 (columns).
# ✔ Each element is indexed using two indices → (row_index, column_index).
# ✔ Can store numbers, strings, or other data types.

# 🔹Creating a 2D NumPy Array?

In [2]:
import numpy as np

arr2 = np.array([[10,20,30],[40,50,60]])
print(arr2)
print(type(arr2))
print(arr2.ndim)

[[10 20 30]
 [40 50 60]]
<class 'numpy.ndarray'>
2


In [8]:
arr2 = np.array([[10,20,30],[40,50,60]],dtype=float)
print(arr2)
print(type(arr2))

[[10. 20. 30.]
 [40. 50. 60.]]
<class 'numpy.ndarray'>


In [15]:
l1 = [[10,20,30],[40,50,60]]
arr2 = np.array(l1,copy=True)
print(arr2)
print(type(arr2))
print(l1)
print(type(l1))
arr2[0][0] = 100
print(arr2)

[[10 20 30]
 [40 50 60]]
<class 'numpy.ndarray'>
[[10, 20, 30], [40, 50, 60]]
<class 'list'>
[[100  20  30]
 [ 40  50  60]]


In [17]:
arr2 = np.array([[10,20,30],[40,50,60]],order='F')
print(arr2)
print(type(arr2))
print(arr2.flags)

[[10 20 30]
 [40 50 60]]
<class 'numpy.ndarray'>
  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [25]:
arr2 = np.array(10,ndmin=2)
print(arr2)
print(arr2.ndim)

[[10]]
2


# 🔹 Properties of a 2D NumPy Array 

In [26]:
# A 2D array in NumPy has various properties that help us understand its structure, dimensions, and type. 
# These properties allow us to efficiently analyze and manipulate arrays.

In [28]:
# 1. ndim – Number of Dimensions
# Tells us how many dimensions (axes) the array has.
# A 2D array always has ndim = 2.

arr2 = np.array([[10,20,30],[40,50,60]])
print(arr2)
print(arr2.ndim)

# Explanation:
# Since arr_2d is a 2D array, it has two axes (rows and columns), so ndim returns 2.

[[10 20 30]
 [40 50 60]]
2


In [30]:
# 2. shape – Dimensions of the Array
# Tells us the number of rows and columns as a tuple (rows, columns).

arr2 = np.array([[10,20,30,40],[50,60,70,80]])
print(arr2)
print("The number of rows and columns the array contains is",arr2.shape)


# Explanation:
# 3 rows
# 3 columns
# So, shape returns (3,3).


[[10 20 30 40]
 [50 60 70 80]]
The number of rows and columns the array contains is (2, 4)


In [31]:
# 3. size – Total Number of Elements
# Tells us the total number of elements in the array (rows × columns).

arr2 = np.array([[10,20,30],[40,50,60]])
print(arr2)
print("The total no. of elements in the array is",arr2.size)

# Explanation:
# The 2D array has 2×3 = 6 elements, so size returns 6.

[[10 20 30]
 [40 50 60]]
The total no. of elements in the array is 6


In [32]:
# 4. dtype – Data Type of Elements
# Tells us the data type of elements inside the array.

arr2 = np.array([[10,20,30],[40,50,60]])
print(arr2)
print("The data type of elements in the array is",arr2.dtype)

# Explanation:
# Since we used integers, the default integer data type (int64 or int32) is assigned.


[[10 20 30]
 [40 50 60]]
The data type of elements in the array is int32


In [37]:
# 5. itemsize – Memory Size of Each Element (in Bytes)
# Tells us how many bytes each element takes in memory.

arr2 = np.array([[10,20,30],[40,50,60]],dtype=float)
print(arr2)
print("The memory occupied by the one element in the bytes when the data type of the elements is float is ",arr2.itemsize)

arr2 = np.array([[10,20,30],[40,50,60]],dtype=int)
print(arr2)
print("The memory occupied by the one element in the bytes when the data type of the elements is int is",arr2.itemsize)

# Explanation:
# If the elements are int64, each element takes 8 bytes.
# If the elements are int32, each element takes 4 bytes.


[[10. 20. 30.]
 [40. 50. 60.]]
The memory occupied by the one element in the bytes when the data type of the elements is float is  8
[[10 20 30]
 [40 50 60]]
The memory occupied by the one element in the bytes when the data type of the elements is int is 4


In [40]:
# 6. nbytes – Total Memory Used by the Array (in Bytes)
# Tells us the total memory occupied by all elements in the array.
# Calculated as:
# nbytes = size × itemsize

arr2 = np.array([[10,20],[30,40]])
print(arr2)
print("The memory occupied by the array is",arr2.nbytes)

# Explanation:
# If itemsize = 8 bytes, then 9 × 8 = 72 bytes.
# If itemsize = 4 bytes, then 9 × 4 = 36 bytes.

[[10 20]
 [30 40]]
The memory occupied by the array is 16


In [43]:
#  7. T – Transpose of the Array
# Flips the rows and columns of the array (i.e., converts arr[i, j] to arr[j, i]).

arr2 = np.array([[10,20,30],[40,50,60],[70,80,90]])
print("The original array is",arr2)
print("The Transpose array is",arr2.T)

# Explanation:
# Row 1 [10, 20, 30] becomes Column 1.
# Row 2 [40, 50, 60] becomes Column 2.
# Row 3 [70, 80, 90] becomes Column 

The original array is [[10 20 30]
 [40 50 60]
 [70 80 90]]
The Transpose array is [[10 40 70]
 [20 50 80]
 [30 60 90]]


In [45]:
# 8. flat – Iterator Over All Elements
# Returns an iterator that allows us to loop through all elements in the array.

arr2 = np.array([[10,20],[30,40]])
print(arr2)

print("Access all the elements of the array using single for loop")
for i in arr2.flat:
    print(i,end=' ')

# Explanation:
# The flat property iterates through the array as a 1D sequence, ignoring rows and columns.

[[10 20]
 [30 40]]
Access all the elements of the array using single for loop
10 20 30 40 

In [51]:
#  9. tolist() – Convert to a Nested Python List
# Converts the NumPy array into a Python list of lists.
t1 = ((10,20,30),(40,50,60))
print(t1)
print(type(t1))
print()

arr2 = np.array(t1)
print(arr2)
print(type(arr2))
print()

print("Converting the numpy 2d array into the 2d list")
l1 = arr2.tolist()
print(l1)
print(type(l1))

# Explanation:
# Converts the NumPy 2D array into a nested Python list.

((10, 20, 30), (40, 50, 60))
<class 'tuple'>

[[10 20 30]
 [40 50 60]]
<class 'numpy.ndarray'>

Converting the numpy 2d array into the 2d list
[[10, 20, 30], [40, 50, 60]]
<class 'list'>


In [53]:
# 10. astype() – Change Data Type of Elements
# Creates a new array with a different data type.

arr2 = np.array([[10,20],[30,40]])
print(arr2)
print()

arr2 = arr2.astype(float)
print(arr2)

[[10 20]
 [30 40]]

[[10. 20.]
 [30. 40.]]


In [62]:
# 11. reshape() – Change the Shape of the Array
# Changes the shape (rows and columns) without changing the data.
# Return the new array with new number of rows and columns
arr2 = np.array([[10,20,30],[40,50,60],[70,80,90]])
print("The array with 3 rows and 3 columns",arr2)

reshape_arr2 = arr2.reshape(1,9)
print("New array with new number of rows and columns is",reshape_arr2)


The array with 3 rows and 3 columns [[10 20 30]
 [40 50 60]
 [70 80 90]]
New array with new number of rows and columns is [[10 20 30 40 50 60 70 80 90]]


In [65]:
# 12. ravel() – Flatten the Array
# The ravel() method in NumPy is used to convert a multi-dimensional array (like a 2D array) into a 1D array. 
# It returns a new 1D view (or a copy) of the original array.
# On modifying the 1D array the changes will be reflected into the 2D array.

arr2 = np.array([[10,20],[30,40]])
print(arr2)
print()

arr1 = arr2.ravel()
print(arr1)
arr1[0] = 1000
print("After modifying the 0th index of the 1D array the 0th index of the 2D array is",arr2)


[[10 20]
 [30 40]]

[10 20 30 40]
After modifying the 0th index of the 1D array the 0th index of the 2D array is [[1000   20]
 [  30   40]]


In [70]:
# 12. flatten() – Flatten the Array
# The flatten() method in NumPy is used to convert a multi-dimensional array (like a 2D array) into a 1D array. 
# It returns a new copy of the original array.
# On modifying the 1D array the changes will not be reflected into the 2D array.

arr2 = np.array([[10,20],[30,40]])
print(arr2)
print()

arr1 = arr2.flatten()
print(arr1)
print()

print("On modifying the 0th index of the 1D array the changes will not reflected into the 2D array")
arr1[0] = 10000
print()

print("1D array",arr1)
print("2D array",arr2)

[[10 20]
 [30 40]]

[10 20 30 40]

On modifying the 0th index of the 1D array the changes will not reflected into the 2D array

1D array [10000    20    30    40]
2D array [[10 20]
 [30 40]]


# Methods of 2D NumPy Arrays 

In [1]:
# A 2D NumPy array is a matrix with rows and columns.
# NumPy provides various methods for manipulating, transforming, and analyzing these arrays.

In [8]:
# 1️⃣ reshape() – Change Shape of an Array
# ✔ Used to change the dimensions of an array without changing the data.

# 🔹 Syntax:
# numpy.ndarray.reshape(new_shape, order='C')

# 🔹 Parameters:
# Parameter	Description
# new_shape	A tuple representing the new shape
# order	'C' (row-wise), 'F' (column-wise), or 'A' (automatic)

import numpy as np

arr1 = np.array([[10,20,30],[40,50,60]])
print(arr1)

print("Reshaping the 2 X 3 numpy array into 1 X 6 array")
reshape_arr =arr1.reshape(1,6,order='F')
print(reshape_arr)
print(reshape_arr.flags)

[[10 20 30]
 [40 50 60]]
Reshaping the 2 X 3 numpy array into 1 X 6 array
[[10 40 20 50 30 60]]
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [11]:
# 2️⃣ transpose() – Swap Rows and Columns
# ✔ Flips the rows and columns of a 2D array.

# 🔹 Syntax:
# numpy.ndarray.transpose()

arr2 = np.array([[10,20,30],[40,50,60]])
print(arr2)

# Return the new array in which rows becomes columns and columns become rows.

arr_transpose = arr2.transpose()
print(arr_transpose)

[[10 20 30]
 [40 50 60]]
[[10 40]
 [20 50]
 [30 60]]


In [14]:
# 3️⃣ flatten() – Convert 2D Array to 1D (Copy)
# ✔ Creates a new 1D array as a copy.

# 🔹 Syntax:
# numpy.ndarray.flatten(order='C')

# 🔹 Parameters:
# Parameter	Description
# order	'C' (row-wise), 'F' (column-wise), 'A' (automatic)

arr2 = np.array([[10,20],[40,50],[60,70]])
print(arr2)

# Creates the copy of all elements of 2D array into 1D array.

print("1D array is")
arr1 = arr2.flatten()
print(arr1)

[[10 20]
 [40 50]
 [60 70]]
1D array is
[10 20 40 50 60 70]


In [15]:
# 4️⃣ ravel() – Convert 2D Array to 1D (View)
# ✔ Returns a flattened view of the array (modifies original if changed).

# 🔹 Syntax:
# numpy.ndarray.ravel(order='C')

arr2 = np.array([[10,20,30],[40,50,60]],order='C')
print(arr2)

arr1 = arr2.ravel()
print(arr1)

[[10 20 30]
 [40 50 60]]
[10 20 30 40 50 60]


In [16]:
# 5️⃣ hstack() – Horizontally Stack Arrays
# ✔ Joins arrays side by side (col-wise).

# 🔹 Syntax:
# np.hstack((array1, array2))

arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

res = np.hstack((arr1,arr2))
print(res)

[[1 2 5 6]
 [3 4 7 8]]


In [18]:
# 6️⃣ vstack() – Vertically Stack Arrays
# ✔ Joins arrays on top of each other (row-wise).

# 🔹 Syntax:
# np.vstack((array1, array2))


arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

res = np.vstack((arr1,arr2))
print(res)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [28]:
# 7️⃣ hsplit() – Split an Array Horizontally
# ✔ Divides an array into multiple sub-arrays column-wise.
# It will return the data in the form of list , which contains the sub-array based on split value passed. 

# 🔹 Syntax:
# np.hsplit(array, num_splits)


arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr1)

#Here it will return the list contains two arrays. 
res = np.hsplit(arr2,2)
print(res)
print(type(res))

res = np.hsplit(arr2,4)
print(res)
print(type(res))
print(res[0],type(res[0]))
print(res[1],type(res[1]))
print(res[2],type(res[2]))
print(res[3],type(res[3]))

[[1 2 3 4]
 [5 6 7 8]]
[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]
<class 'list'>
[array([[1],
       [5]]), array([[2],
       [6]]), array([[3],
       [7]]), array([[4],
       [8]])]
<class 'list'>
[[1]
 [5]] <class 'numpy.ndarray'>
[[2]
 [6]] <class 'numpy.ndarray'>
[[3]
 [7]] <class 'numpy.ndarray'>
[[4]
 [8]] <class 'numpy.ndarray'>


In [32]:
# 8️⃣ vsplit() – Split an Array Vertically
# ✔ Divides an array into multiple sub-arrays row-wise.

# 🔹 Syntax:
# np.vsplit(array, num_splits)

arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)

res = np.vsplit(arr2,2)
print(res)

# this give error bcz we can't divide the array into 3 rows as the original array itself does not contains the 3 rows.
# res = np.vsplit(arr2,3)
# print(res)

[[1 2 3 4]
 [5 6 7 8]]
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


In [36]:
# 9️⃣ concatenate() – Merge Arrays
# ✔ Joins two or more arrays along a specified axis.
# return the new array which the concatenation of the two array,or we can say it contains all the elements of two arrays.

# 🔹 Syntax:
# np.concatenate((arr1, arr2), axis)

# axis = 0 means row
# axis = 1 means column

arr1 = np.array([[1,2,3,4],[5,6,7,8]])
arr2 = np.array([[9,10,11,12],[13,14,15,16]])

print("Concatencated two arrays row-wise")
res = np.concatenate((arr1,arr2),axis=0)
print(res)

print("Concatencated two arrays column-wise")
res = np.concatenate((arr1,arr2),axis=1)
print(res)

Concatencated two arrays row-wise
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Concatencated two arrays column-wise
[[ 1  2  3  4  9 10 11 12]
 [ 5  6  7  8 13 14 15 16]]


In [42]:
# 🔟 unique() – Find Unique Elements
# ✔ Finds the unique elements in an array.
#  return the 1D array which contains unique elements.

# 🔹 Syntax:
# np.unique(array)

arr1 = np.array([[10,20,30],[40,20,30]])
print(arr1)

res = np.unique(arr1)
print(res)
print(type(res))
print(res.ndim)

[[10 20 30]
 [40 20 30]]
[10 20 30 40]
<class 'numpy.ndarray'>
1


In [48]:
# 1️⃣1️⃣ where() – Find Indices Based on a Condition
# ✔ Returns indices where the condition is True.
# Return the tuple containing array which stores the indices for which the condition returns true. 

# 🔹 Syntax:
# np.where(condition)

arr1 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr1)
print()

indices1  = np.where(arr1>2)
print(indices1)
print(type(indices1))
print()

indices2 = np.where(arr1>6)
print(indices2)
print(type(indices2))

[[1 2 3 4]
 [5 6 7 8]]

(array([0, 0, 1, 1, 1, 1], dtype=int64), array([2, 3, 0, 1, 2, 3], dtype=int64))
<class 'tuple'>

(array([1, 1], dtype=int64), array([2, 3], dtype=int64))
<class 'tuple'>


In [54]:
# 1️⃣2️⃣ clip() – Limit Values to a Range
# ✔ Limits the values between min and max.

# Syntax:
# np.clip(array, min, max)

arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)

# It will return the new 2D array, if any value less than the min value then it set to min
# and if any value is greater than the max value then set to max 
res = arr2.clip(3,6)
print(res)

res = np.clip(arr2,2,6)
print(res)

[[1 2 3 4]
 [5 6 7 8]]
[[3 3 3 4]
 [5 6 6 6]]
[[2 2 3 4]
 [5 6 6 6]]


In [14]:
# 13. The astype() method in NumPy is used to convert the data type (dtype) of a NumPy array to another data type. 
# It creates a new array with the specified dtype while keeping the original array unchanged.

# 🔹 Syntax
# numpy.ndarray.astype(dtype, order='K', casting='unsafe', subok=True, copy=True)

# 🔹 Parameters
# Parameter	Description
# dtype	The target data type (e.g., int, float, bool, complex)
# order	'C' (row-major), 'F' (column-major), 'A' (automatic), 'K' (keep original order)
# casting	Controls type conversion: 'no', 'equiv', 'safe', 'same_kind', 'unsafe'
# subok	If True, subclasses are passed through; otherwise, a base class is used
# copy	If True, always returns a new array; if False, returns a new array only if necessary


import numpy as np

arr2d = np.array([[10,20],[40,50]],dtype = float)
print(arr2d)
print(arr2d.dtype)
print()

res_2d = arr2d.astype(int,copy=True)
print(res_2d)
print()

res_2d[0][0] = 100
print(res_2d)
print(arr2d)
print()

# If copy=True (default), a new array is always created.
# If copy=False, NumPy avoids making a copy when possible (if the dtype remains unchanged).

[[10. 20.]
 [40. 50.]]
float64

[[10 20]
 [40 50]]

[[100  20]
 [ 40  50]]
[[10. 20.]
 [40. 50.]]



In [21]:
# 14 copy(). Method in NumPy for 2D Arrays

# The copy() method in NumPy is used to create an explicit copy of an array. 
# This ensures that modifications to the new array do not affect the original one.

# 🔹 Syntax
# new_array = old_array.copy(order='C')

# 🔹 Parameters
# Parameter	Description	Default
# order	Specifies memory layout of the copied array. Options: 'C', 'F', 'A', 'K'	'C'


arr2d = np.array([[10,20],[30,40]])
print("Original Array",arr2d)
print()

copy_arr2d = np.copy(arr2d,order='C')
print("Copy Array",copy_arr2d)

copy_arr2d[0][0] = 1000
print()

print("After changing the copy array 0th row and 0th column the array is",copy_arr2d)
print()
print("The chnages done in the copy array is not reflected into the original array",arr2d)

Original Array [[10 20]
 [30 40]]

Copy Array [[10 20]
 [30 40]]

After changing the copy array 0th row and 0th column the array is [[1000   20]
 [  30   40]]

The chnages done in the copy array is not reflected into the original array [[10 20]
 [30 40]]


In [27]:
# 15.view() Method 
# The view() method in NumPy allows us to create a new view (or shallow copy) of an array without copying the actual data. 
# This means that changes to the view will reflect in the original array.

# 🔹 Syntax
# new_view = old_array.view(dtype=None)

# 🔹 Parameters
# Parameter	Description	Default
# dtype	Changes the data type (dtype) of the view without modifying original data.	None (Keeps same dtype)


arr2d = np.array([[10,20,30,40],[50,60,70,80]])
print(arr2d)
print()

new_view = arr2d.view(dtype=float)
print("On converting the data type from int to float we don't get the original values instead we get the binary value as float",new_view)

# Issue: Misaligned Data Representation
# When you use .view(dtype=float), NumPy does not actually convert the numbers from integers to floats. 
# Instead, it reinterprets the underlying binary data as floating-point numbers. 
# Since int and float are stored differently in memory, this leads to unexpected values.

[[10 20 30 40]
 [50 60 70 80]]

On converting the data type from int to float we don't get the original values instead we get the binary value as float [[4.24399158e-313 8.48798317e-313]
 [1.27319747e-312 1.69759663e-312]]


In [33]:
arr2d = np.array([[10,20,30,40],[50,60,70,80]])
new_view = arr2d.view()
print(new_view)

new_view[0][0] = 1000
print("After changing the 0th row and column of the view array is",new_view)
print()
print("The changes done in the view affect the original array",arr2d)


[[10 20 30 40]
 [50 60 70 80]]
After changing the 0th row and column of the view array is [[1000   20   30   40]
 [  50   60   70   80]]

The changes done in the view affect the original array [[1000   20   30   40]
 [  50   60   70   80]]


In [10]:
# 17.reshape() 
# The reshape() method in NumPy allows us to change the shape of an array without changing its data. 
# It is commonly used to convert a 1D array into a 2D array or change the dimensions of an existing 2D array.

# 🔹 Syntax
# numpy.ndarray.reshape(new_shape, order='C')

# 🔹 Parameters
# Parameter	Description
# new_shape	Tuple specifying the new shape (rows, columns). One dimension can be -1, which means NumPy will automatically infer its value.
# order	Specifies how elements should be read and placed in the reshaped array. Options: 'C', 'F', or 'A'. Default is 'C'.

arr1 = np.array([10,20,30,40,50,60])
print(arr1)

arr2 = arr1.reshape(2,3)
print(arr2)
print(arr1)


# When we pass -1 as the arugment in the reshape method then it is used to flatten multidimensional array into 1D array.
new_arr = arr2.reshape(-1)
print(new_arr)



# When we pas -1 as the arugment in the reshape method either as the rows or the columns then it will automatically calculate the either rows or columns.
new_arr = arr1.reshape((-1,3))
print(new_arr)

[10 20 30 40 50 60]
[[10 20 30]
 [40 50 60]]
[10 20 30 40 50 60]
[10 20 30 40 50 60]
[[10 20 30]
 [40 50 60]]


In [17]:
# 18. flatten()
# The flatten() method converts a multi-dimensional array (e.g., 2D) into a 1D array by copying the data into a new array.

# Syntax
# numpy.ndarray.flatten(order='C')

# 🔹 Parameters
# Parameter	Type	Default	Description
# order	str	'C'	Specifies how the array is flattened. Options: 'C', 'F', 'A', 'K'

arr2 = np.array([[10,20,30],[40,50,60]])
print(arr2)

arr1 = arr2.flatten()
print(arr1)

arr1[0] = 1000
print(arr1)
print(arr2)

[[10 20 30]
 [40 50 60]]
[10 20 30 40 50 60]
[1000   20   30   40   50   60]
[[10 20 30]
 [40 50 60]]


In [20]:
# 19.ravel()
# The ravel() method flattens a multi-dimensional array (e.g., 2D) into a 1D array while trying to return a view of the original array if possible (to save memory). 
# If a view isn’t possible, it returns a copy instead.

# Syntax
# numpy.ndarray.ravel(order='C')

# 🔹 Parameters
# Parameter	Type	Default	Description
# order	str	'C'	Specifies how the array is flattened. Options: 'C', 'F', 'A', 'K'


arr2 = np.array([[10,20,30],[40,50,60]])
print(arr2)
print()

arr1 = arr2.ravel()
print(arr1)
print()

arr1[0]= 1000
print(arr1)
print()
print(arr2)

[[10 20 30]
 [40 50 60]]

[10 20 30 40 50 60]

[1000   20   30   40   50   60]

[[1000   20   30]
 [  40   50   60]]


In [25]:
# 20. transpose()
# The transpose() method in NumPy swaps the axes (dimensions) of an array, 
# effectively flipping the rows and columns in a 2D array.

# It return the view of the array which means when the changes will done on the tranpose array it will reflect on original array.

arr2 = np.array([[10,20,30],[40,50,60]])
print(arr2)
print()

new_arr =  arr2.transpose()
new_arr[0][1] = 2000
print(new_arr)
print()
print(arr2)

[[10 20 30]
 [40 50 60]]

[[  10 2000]
 [  20   50]
 [  30   60]]

[[  10   20   30]
 [2000   50   60]]


In [30]:
# 🔹 For a 2D array, the only valid values for axes are:
# (0, 1) → Keep the array the same (no change).
# (1, 0) → Transpose the array (swap rows & columns).

arr2 = np.array([[10,20,30],[40,50,60],[70,80,90]])
print("Original Array",arr2)

transpose_arr = arr2.transpose(1,0)
print("Transposed Array",transpose_arr)

Original Array [[10 20 30]
 [40 50 60]
 [70 80 90]]
Transposed Array [[10 40 70]
 [20 50 80]
 [30 60 90]]


In [31]:
# 21.sum() Method
# The sum() method in NumPy computes the sum of array elements along a given axis or the entire array.

# Syntax
# numpy.ndarray.sum(axis=None, dtype=None, out=None, keepdims=False)

# Parameter	Description
# axis	The axis along which to sum the elements (0 for columns, 1 for rows, None for the entire array).
# dtype	The data type of the output sum (e.g., np.float64, np.int32).
# out	Alternative array where the result is stored.
# keepdims	If True, keeps the original dimensions (result stays 2D).


arr2 = np.array([[10,20,30],[40,50,60]])
print(arr2)
print()

res = arr2.sum()
print("The summation of all the elements of the array is",res)

[[10 20 30]
 [40 50 60]]

The summation of all the elements of the array is 210


In [32]:
res = arr2.sum(dtype=float)
print("The summation of all the elements of the array in float",res)

The summation of all the elements of the array in float 210.0


In [34]:
# Here the axis 0 means add is performed column wise.
res = arr2.sum(dtype=float,axis=0)
print(res)
print(type(res))

[50. 70. 90.]
<class 'numpy.ndarray'>


In [35]:
# Here the axis 1 means addition is performed row wise.
res = arr2.sum(axis=1)
print(res)

[ 60 150]


In [37]:
# Specifying the array in which the output must be store.
# arr2.sum(out=arr2)
# print(arr2)

# ValueError: output parameter for reduction operation add has the wrong number of dimensions: Found 2 but expected 0


# Why Does This Error Occur?
# The out parameter should match the output shape
# When sum() is called without an axis (axis=None), it returns a single scalar value (not an array).
# But arr2 is a 2D array, which cannot hold a single scalar value.
# NumPy expects out to have the same shape as the result.


In [42]:
arr1 = np.zeros((3,))
print(arr1)

# Here the addition is performed colums which return 1D array containing 3 values
# As the arr1 array have shape required to hold the result return from sum method so we can hold the data into it.
arr2.sum(out=arr1,axis=0)
print(arr1)

[0. 0. 0.]
[50. 70. 90.]


In [43]:
# 22.numpy.mean() – Compute the Mean of an Array
# The numpy.mean() function calculates the arithmetic mean (average) of an array along the specified axis.

# 🔹 Syntax
# numpy.mean(a, axis=None, dtype=None, out=None, keepdims=False, where=True)

In [46]:
# Parameters
# 1️⃣ a (Required)
# The input array-like object for which we need to calculate the mean.
# Can be a list, tuple, or NumPy array.

arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2.mean())
# The mean of all elements (1+2+3+4+5+6) / 6 = 3.5.

[[1 2 3]
 [4 5 6]]
3.5


In [49]:
# 2️⃣ axis (Optional, Default = None)
# Specifies the axis along which the mean is computed:
# axis=None → Computes mean of all elements (default).
# axis=0 → Computes mean column-wise (downwards).
# axis=1 → Computes mean row-wise (horizontally).

arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

res = arr2.mean(axis=0)
print("Column wise mean of the array",res)

res = arr2.mean(axis=1)
print("Row wise mean of the array",res)

# axis=0: Mean column-wise → [(1+4)/2, (2+5)/2, (3+6)/2] = [2.5, 3.5, 4.5]
# axis=1: Mean row-wise → [(1+2+3)/3, (4+5+6)/3] = [2.0, 5.0]

[[1 2 3]
 [4 5 6]]
Column wise mean of the array [2.5 3.5 4.5]
Row wise mean of the array [2. 5.]


In [54]:
# 3️⃣ dtype (Optional, Default = None)
# Specifies the data type for computation.
# If not given, it uses:
# float64 for int input
# Same dtype for float input

arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

res = arr2.mean(dtype=np.float32)
print(res)
print(type(res))

[[1 2 3]
 [4 5 6]]
3.5
<class 'numpy.float32'>


In [55]:
# 4️⃣ out (Optional, Default = None)
# Used to store the result in a given array.
# Must have the same shape as the output.

output_arr = np.ones((3,))
print(output_arr)

arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

arr2.mean(out=output_arr,axis=0)
print(output_arr)

[1. 1. 1.]
[[1 2 3]
 [4 5 6]]
[2.5 3.5 4.5]


In [60]:
# 5️⃣ keepdims (Optional, Default = False)
# If True, retains the same number of dimensions as input.
# Otherwise, the result is broadcasted to fewer dimensions.

arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

res1 = arr2.mean(axis=0)
print("Return the data in the form of 1D array",res1)

res2 = arr2.mean(axis=0,keepdims=True)
print("Return the data in the form of original array shape",res2)


[[1 2 3]
 [4 5 6]]
Return the data in the form of 1D array [2.5 3.5 4.5]
Return the data in the form of original array shape [[2.5 3.5 4.5]]


In [ ]:
# Both std() (Standard Deviation) and var() (Variance) are used to measure the spread of data in an array.

# 23.std() – Compute the Standard Deviation

# 🔹 Syntax:
# numpy.std(a, axis=None, dtype=None, out=None, ddof=0, keepdims=False)

# 🔹 Parameters:
# Parameter	Description
# a	Input 2D array.
# axis	Axis along which to compute the standard deviation. Default is None (global std).
# dtype	Data type for computations. Default is the same as input.
# out	Optional output array to store the result. Must match the expected shape.
# ddof	"Delta Degrees of Freedom" (default 0). Use ddof=1 for sample standard deviation.
# keepdims	If True, keeps the reduced dimension as 1.

# 🔹 Return Type:
# NumPy scalar (numpy.float64) if axis=None
# NumPy array (numpy.ndarray) if axis is specified

In [61]:
# Standard Deviation of Entire 2D Array

arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

res = arr2.std()
print(res)

# Since axis=None, it returns a single scalar (numpy.float64).

[[1 2 3]
 [4 5 6]]
1.707825127659933


In [68]:
# Standard Deviation Along an Axis

# axis 0 means columns wise std()

arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
print()

res = arr2.std(axis=0)
print("Column Wise",res)
print()

# When axis is 1.
# axis 0 means row wise std()

arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
print()

res = arr2.std(axis=1)
print("Row Wise",res)
print()


# If axis=0, we get a 1D array where each column's std is calculated.
# If axis=1, we get a 1D array where each row's std is calculated.

[[1 2 3]
 [4 5 6]]

Column Wise [1.5 1.5 1.5]

[[1 2 3]
 [4 5 6]]

Row Wise [0.81649658 0.81649658]



In [70]:
# Using ddof=1 (Sample Standard Deviation)

arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
print()

res = arr2.std(axis=0,ddof=1)
print(res)

# For sample std deviation (ddof=1), variance is divided by N-1 instead of N.

[[1 2 3]
 [4 5 6]]

[2.12132034 2.12132034 2.12132034]


In [75]:
#  Using keepdims=True

output = np.ones(3,)
print(output)

arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
print()

res = arr2.std(axis=0,keepdims=True)
print(res)

# Keeps reduced dimensions intact instead of collapsing them.

[1. 1. 1.]
[[1 2 3]
 [4 5 6]]

[[1.5 1.5 1.5]]


In [77]:
# 24.var() – Compute the Variance

# 🔹 Syntax:
# numpy.var(a, axis=None, dtype=None, out=None, ddof=0, keepdims=False)

# ✔ Same parameters as std(), but it returns the variance instead.

# Variance of Entire 2D Array

arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
print()

res = arr2.var()
print(res)

[[1 2 3]
 [4 5 6]]

2.9166666666666665


In [79]:
# Variance Along an Axis

arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
print()

res = arr2.var(axis=0)
print(res)

res = arr2.var(axis=1)
print(res)

[[1 2 3]
 [4 5 6]]

[2.25 2.25 2.25]
[0.66666667 0.66666667]


In [80]:
# Using ddof=1 (Sample Variance)

arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
print()

res = arr2.var(ddof=1)
print(res)

[[1 2 3]
 [4 5 6]]

3.5


In [82]:
# Using keepdims=True

arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
print()

# Keep in the answer in the same array shape as the original array shape.
res = arr2.var(keepdims=True)
print(res)

[[1 2 3]
 [4 5 6]]

[[2.91666667]]


In [1]:
# 24.min() – Find Minimum Value
# return the minimum value from the array along specific access or from the entire array.

# 🔹 Syntax:
# numpy.min(a, axis=None, out=None, keepdims=False, initial=None, where=True)

# 🔹 Parameters:
# Parameter	Description
# a	The input 2D array.
# axis	The axis along which to compute the minimum. Default is None (computes the global minimum).
# out	Optional output array where the result is stored.
# keepdims	If True, keeps the reduced dimensions instead of collapsing them.
# initial	A starting value for comparison (useful for empty slices).
# where	A boolean mask that determines which elements to consider.

In [5]:
# i.Minimum Value in Entire 2D Array

arr2 = np.array([[3,2,1],[7,8,9]])
print(arr2)
print("The minimum value from the entire array is",arr2.min())

# Since axis=None, it returns a single scalar, which is the minimum value in the entire array.

[[3 2 1]
 [7 8 9]]
The minimum value from the entire array is 1


In [6]:
# ii.Minimum Value Along an Axis

arr2 = np.array([[3,2,1],[9,1,10]])
print(arr2)

print("Minimum value along each column",arr2.min(axis=0))
print("Minimum value along each row",arr2.min(axis=1))

# If axis=0, it returns the minimum of each column.
# If axis=1, it returns the minimum of each row.

[[ 3  2  1]
 [ 9  1 10]]
Minimum value along each column [3 1 1]
Minimum value along each row [1 1]


In [10]:
# iii. Using keepdims=True

arr2 = np.array([[1,2,3],[4,5,0]])
print(arr2)
print("Keeping the dimension of the original array ",arr2.min(keepdims=True,axis=0))

# Keeps the reduced dimension instead of collapsing it.

[[1 2 3]
 [4 5 0]]
Keeping the dimension of the original array  [[1 2 0]]


In [19]:
# iv.Using initial

arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

print("finding the minimum less then the specified value",arr2.min(initial=-1))
# If none value is found lesser than the specified value then return the specified value.
# Allows specifying a minimum starting value.


arr2 = np.array([[1,2,3],[4,5,6]])
# if the value in the any column is greater than specified value than the value in that column is replaced with the specified value.
print(arr2.min(axis=0,keepdims=True,initial=2))


arr2 =np.array([[1,2,3],[4,5,6]])
# if the value in the any row is greater than specified value than the value in that row is replaced with the specified value.
print(arr2.min(axis=0,keepdims=True,initial=2))
print(arr2.min(axis=1,keepdims=True,initial=2))

[[1 2 3]
 [4 5 6]]
finding the minimum less then the specified value -1
[[1 2 2]]
[[1]
 [2]]


In [25]:
# v.Using where

# arr2 =np.array([[1,2,3],[4,5,6]])
# mask = arr2>4
# finding the first minimum value from the array that statisfy the condition.
# print(arr2.min(where=mask))

# "ValueError: reduction operation 'minimum' does not have an identity, so to use a where mask one has to specify 'initial'"
# because when you use the where parameter, NumPy needs a default value (identity element) to compare against if there are no True values in the mask.
# The min() function does not have a default identity value that works for all cases.

# What does where=mask do?
# mask = arr2 > 4 creates a boolean mask:
# [[False, False, False],
#  [False,  True,  True]]
# This means only arr2[1,1] = 5 and arr2[1,2] = 6 are considered.
# However, the min() function needs an initial value to start the comparison.

# Why does min() fail?
# Without an initial value, NumPy does not know what to return if there are no True values in where.
# The error is triggered when where is used without initial, because min() does not have a default comparison value (unlike sum() which starts from 0).

In [30]:
arr2 = np.array([[1,2,3],[4,5,6]])
mask = arr2>4

# Initial is required when we use where bcz nump needs a default value to compare  against if there is no true values in the mask. 
print("the minimum value from the array which statisfy the condition where value > 4 is",arr2.min(where=mask,initial=100))


the minimum value from the array which statisfy the condition where value > 4 is 5


In [32]:
# 25.max() – Find Maximum Value

# 🔹 Syntax:
# numpy.max(a, axis=None, out=None, keepdims=False, initial=None, where=True)
# ✔ Same parameters as min(), but finds the largest value instead.

#  i.Maximum Value in Entire 2D Array

arr2 = np.array([[1,2,3,4],[10,20,30,1]])
print(arr2)
print("The maximum value from the array is",arr2.max())

[[ 1  2  3  4]
 [10 20 30  1]]
The maximum value from the array is 30


In [33]:
# ii.Maximum Value Along an Axis

arr2 = np.array([[1,2,3,4],[10,20,30,1]])
print(arr2)

print("Maximum value along each column",arr2.max(axis=0))
print("Maximum value along each row",arr2.max(axis=1))

[[ 1  2  3  4]
 [10 20 30  1]]
Maximum value along each column [10 20 30  4]
Maximum value along each row [ 4 30]


In [35]:
#  iii.Using keepdims=True

arr2 = np.array([[1,2,3,4],[10,20,30,1]])
print(arr2)

print(arr2.max(keepdims=True))
print(arr2.max(keepdims=True,axis=0))
print(arr2.max(keepdims=True,axis=1))

[[ 1  2  3  4]
 [10 20 30  1]]
[[30]]
[[10 20 30  4]]
[[ 4]
 [30]]


In [38]:
# iv.Using initial

arr2 = np.array([[1,2,3,4],[10,20,30,1]])
print(arr2)

print("finding the maximum value greater than the specified value in the initial parameter if not return the specified value",arr2.max(initial=1))

[[ 1  2  3  4]
 [10 20 30  1]]
finding the maximum value greater than the specified value in the initial parameter if not return the specified value 30


In [44]:
# v.Using where


arr2 = np.array([[1,2,3,4],[10,20,30,1]])
print(arr2)

mask = arr2>20
print("the value which is just greater than 20 is",arr2.max(where=mask,initial=10,keepdims=True))


[[ 1  2  3  4]
 [10 20 30  1]]
the value which is just greater than 20 is [[30]]


In [45]:
# 26.argmin() – Find the Index of the Minimum Value

# Syntax:
# numpy.ndarray.argmin(axis=None, out=None, keepdims=False)

# 🔹 Parameters:
# Parameter	Description
# axis	Determines whether to compute along rows (axis=1), columns (axis=0), or on the entire array (axis=None - default).
# out	An optional output array to store the result (must have the correct shape).
# keepdims	If True, keeps the output shape similar to the input array.


arr2 = np.array([[1,2,3],[6,7,8]])
print(arr2)

# i.Finding Minimum Index Value

print("The index which contains minimum value is",arr2.argmin())

[[1 2 3]
 [6 7 8]]
The index which contains minimum value is 0


In [50]:
# ii.Using axis

arr2 = np.array([[50,40,60],[10,20,30]])
print(arr2)

print(arr2.argmin(axis=0))
print(arr2.argmin(axis=1))

[[50 40 60]
 [10 20 30]]
[1 1 1]
[1 0]


In [53]:
# iii. Using Keepdmins

arr2 = np.array([[10,20,30],[1,2,3]])
print(arr2.argmin(keepdims=True))

[[3]]


In [56]:
# 27.argmax() – Find the Index of the Maximum Value

#  Syntax:
# numpy.ndarray.argmax(axis=None, out=None, keepdims=False)
# (Same parameters as argmin().)

# i.Finding Maximum Index

arr2 = np.array([[1,2,3],[10,200,300]])
print(arr2)

print("The index at which the maximum value is present is",arr2.argmax())

[[  1   2   3]
 [ 10 200 300]]
The index at which the maximum value is present is 5


In [61]:
# ii.Using axis

arr2 = np.array([[1,2,3],[10,200,300]])
print(arr2)
print()

print("Index which contains minimum value along each column from the array",arr2.argmax(axis=0))
print()
print("Index which contains minimum value along each row from the array",arr2.argmax(axis=1))

[[  1   2   3]
 [ 10 200 300]]

Index which contains minimum value along each column from the array [1 1 1]

Index which contains minimum value along each row from the array [2 2]


In [65]:
# iii. Using keepdimns

arr2 = np.array([[10,20,30],[30,40,50]])
print(arr2)

print("the maximum value from the array is at",arr2.argmax(keepdims=True),"index")

[[10 20 30]
 [30 40 50]]
the maximum value from the array is at [[5]] index


In [69]:
# 28.sort() Method for 2D Arrays in NumPy
# The numpy.sort() method sorts the elements of a 2D array along a specified axis. 
# By default, sorting is done along the last axis (axis=-1, i.e., along rows).
# Sort the original array does not return anything.

# Syntax
# numpy.sort(a, axis=-1, kind=None, order=None)

# 🔹 Parameters and Explanation
# Parameter	Description
# a	The input NumPy array (must be 2D in this case).
# axis	Specifies the axis along which to sort.
# axis=0 → Sort each column (vertically).
# axis=1 (default) → Sort each row (horizontally).
# axis=None → Flattens the array and sorts all elements.
# kind	Sorting algorithm to use:
# "quicksort" (default), "mergesort", "heapsort", "stable".
# order	Used only for structured arrays (not applicable to normal 2D arrays).


# i. Default Sorting (Sort Rows)

arr2 = np.array([[4,2,3,1],[4,59,10,2]])
print(arr2)
arr2.sort()
print("After sorting",arr2)

[[ 4  2  3  1]
 [ 4 59 10  2]]
After sorting [[ 1  2  3  4]
 [ 2  4 10 59]]


In [73]:
# ii. using Axis = 0
arr2 = np.array([[4,2,3,1],[4,59,10,2]])
print(arr2)
arr2.sort(axis=0)
print("After Sorting",arr2)

[[ 4  2  3  1]
 [ 4 59 10  2]]
After Sorting [[ 4  2  3  1]
 [ 4 59 10  2]]


In [76]:
# iii. Using Kind 
arr2 = np.array([[4,2,3,1],[4,59,10,2]])
print("Original Array",arr2)

arr2.sort(kind='heapsort')
print("Used HeapSort to sort the array",arr2)

Original Array [[ 4  2  3  1]
 [ 4 59 10  2]]
Used HeapSort to sort the array [[ 1  2  3  4]
 [ 2  4 10 59]]


In [78]:
# iv. Using axis = none
# When axis is none then it flatten the array and sort it.

arr2 = np.array([[8,7,6,5],[4,3,2,1]])
print(arr2)

new_arr = np.sort(arr2,axis=None)
print(new_arr)

[[8 7 6 5]
 [4 3 2 1]]
[1 2 3 4 5 6 7 8]


In [83]:
# v. Using Order
# the order parameter is used only for structured arrays (arrays with named fields).

dtype = [('name','S10'),('marks',int)]
data = np.array([('Alice',90),('Bob',85),('koko',87)],dtype=dtype)

res = np.sort(data,order='marks')
print(res)

[(b'Bob', 85) (b'koko', 87) (b'Alice', 90)]


In [6]:
# 29.The numpy.concatenate() method is used to join multiple NumPy arrays along a specified axis.

# Syntax
# numpy.concatenate((array1, array2, ...), axis=0, out=None, dtype=None, casting="same_kind")

# 🔹 Parameters and Explanation
# Parameter	Description
# (array1, array2, ...)	A tuple of arrays to be concatenated.
# All arrays must have the same shape except in the concatenation axis.
# axis	Specifies the axis along which to concatenate.
# axis=0 (default) → Join along rows (vertical stacking)
# axis=1 → Join along columns (horizontal stacking)
# out	Optional. If specified, the result is stored in this provided array.
# dtype	Optional. Specifies the desired data type for the output array.
# casting	Controls type casting when dtype is provided. Options: "no", "equiv", "safe", "same_kind", "unsafe".


arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [7]:
# i.Default Concatenation (Along Rows)
res = np.concatenate((arr1,arr2))
print(res)

# By default (axis=0), NumPy stacks arrays vertically (rows are added).

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [9]:
# ii.Concatenating Along Columns (axis=1)

res = np.concatenate((arr1,arr2),axis=1)
print(res)

# With axis=1, arrays are joined column-wise (side-by-side).

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [10]:
# iii.Concatenating 1D Arrays into 2D (axis=None)

# It is used to flatten the array.
res = np.concatenate((arr1,arr2),axis=None)
print(res)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [12]:
# 30.The numpy.unique() method is used to find the unique elements in a NumPy array. 
# It returns an array of unique elements, and optionally, additional information like their counts and indices.

# Syntax
# numpy.unique(arr, return_index=False, return_inverse=False, return_counts=False, axis=None)

# 🔹 Parameters and Explanation
# Parameter	Description
# arr	The input NumPy array (can be 1D, 2D, or higher-dimensional).
# return_index	If True, returns the indices of the first occurrence of each unique element.
# return_inverse	If True, returns an array of indices that reconstruct arr from unique.
# return_counts	If True, returns the count of each unique element.
# axis	If None (default), flattens the array and finds unique elements.
# If axis=0, finds unique rows.
# If axis=1, finds unique columns.


# i.Finding Unique Elements in a 2D Array

arr2 = np.array([[1,2,3],[4,1,1]])
print(arr2)

# Return the 1D array contains the unique elements
print(np.unique(arr2))

[[1 2 3]
 [4 1 1]]
[1 2 3 4]


In [14]:
# ii.Using return_index=True
# Returns the indices of the first occurrence of each unique element.

arr2 = np.array([[1,2,3],[4,1,1]])
print(arr2)

print(np.unique(arr2,return_index=True))
# The second output shows the indices where the first occurrence of each unique element appears in the flattened array.



[[1 2 3]
 [4 1 1]]
(array([1, 2, 3, 4]), array([0, 1, 2, 3], dtype=int64))


In [20]:
# iii.Using return_counts=True
# Returns the count of each unique element.

arr2 = np.array([[1,2,3],[1,2,3]])
print(arr2)

print(np.unique(arr2,return_counts=True))


[[1 2 3]
 [1 2 3]]
(array([1, 2, 3]), array([2, 2, 2], dtype=int64))


In [30]:
# iv.Using axis=0 (Unique Rows)
# If axis=0, the function finds unique rows.

arr2 = np.array([[1,1,1],[2,2,2],[6,6,6]])
print(arr2)

print(np.unique(arr2,axis=0))

# axis=0 means we are checking for duplicate rows.
# Since all rows are already unique, the function simply returns the original array as is.

[[1 1 1]
 [2 2 2]
 [6 6 6]]
[[1 1 1]
 [2 2 2]
 [6 6 6]]


In [33]:
#  Using axis=1 (Unique Columns)
# If axis=1, the function finds unique columns.

arr2 = np.array([[1,1,1],[2,2,2],[3,3,3]])
print(arr2)


print(np.unique(arr2,axis=1))
# axis=0 means we are checking for duplicate columns.

[[1 1 1]
 [2 2 2]
 [3 3 3]]
[[1]
 [2]
 [3]]


In [5]:
# 31.numpy.where() for 2D Arrays – Detailed Explanation
# The numpy.where() function is used to find the indices where a condition is True or to replace values based on a condition.

# Syntax
# numpy.where(condition, [x, y])

# 🔹 Parameters
# condition → A boolean condition to check.
# x (optional) → Values to use where condition is True.
# y (optional) → Values to use where condition is False.

# Return Type
# If only condition is provided → Returns the indices where the condition is True.
# If x and y are provided → Returns a new array with values from x where the condition is True and from y where it's False.



# i.Finding Indices Where Condition is True
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)

res = np.where(arr2>4)
print(res)
print(type(res))
print(res[0])
print(res[1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(array([1, 1, 2, 2, 2], dtype=int64), array([1, 2, 0, 1, 2], dtype=int64))
<class 'tuple'>
[1 1 2 2 2]
[1 2 0 1 2]


In [6]:
# ii.Replacing Values Based on a Condition

arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)

res = np.where(arr2>4,100,200)
print(res)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[200 200 200]
 [200 100 100]
 [100 100 100]]


In [9]:
# 32.The numpy.clip() method limits (clips) values in an array to a specified range.

# Syntax
# numpy.clip(a, a_min, a_max, out=None)

# 🔹 Parameters
# Parameter	Description
# a	The input array (2D array in this case).
# a_min	The minimum value allowed in the output array. Values smaller than this are replaced with a_min.
# a_max	The maximum value allowed in the output array. Values larger than this are replaced with a_max.
# out (optional)	The array to store the result. It must have the same shape as a. If None, a new array is returned.

# Return Type
# A new clipped array (if out=None).
# The same out array with clipped values (if out is specified).


arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Original Array",arr1)

res = np.clip(arr1,2,8)
print("New Clipped Array",res)

Original Array [[1 2 3]
 [4 5 6]
 [7 8 9]]
New Clipped Array [[2 2 3]
 [4 5 6]
 [7 8 8]]


In [10]:
# 33.  numpy.all() – Check if All Elements Are True
# The numpy.all() function returns True if all elements in the array (or along a specified axis) are True (nonzero).

# 🔹 Syntax
# numpy.all(a, axis=None, out=None, keepdims=False, where=True)

# 🔹 Parameters
# Parameter	Description
# a	The input 2D array.
# axis (optional)	The axis along which to perform the check. Default is None (checks the entire array).
# out (optional)	The output array where the result is stored. Must be the same shape as the expected output.
# keepdims (optional, default=False)	If True, retains reduced dimensions (useful for broadcasting).
# where (optional)	A condition to check only selected elements.


# i.Check if All Elements Are Nonzero (True)

arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

res = np.all(arr2)
print(res)

[[1 2 3]
 [4 5 6]]
True


In [12]:
# ii.Using axis Parameter

arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

print(np.all(arr2,axis=0))
print(np.all(arr2,axis=1))

[[1 2 3]
 [4 5 6]]
[ True  True  True]
[ True  True]


In [13]:
# iii.Using keepdims

arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

res = np.all(arr2,keepdims=True)
print(res)


[[1 2 3]
 [4 5 6]]
[[ True]]


In [14]:
# iv.Using where Parameter

arr2 = np.array([[1,2,3],[4,0,6]])
print(arr2)

mask = np.array([[True,True,True],[True,False,True]])

res = np.all(arr2,where=mask,keepdims=True)
print(res)


# The where parameter applies np.all() only on True positions in mask, ignoring False positions.

[[1 2 3]
 [4 0 6]]
[[ True]]


In [15]:
# 34.numpy.any() – Check if At Least One Element Is True
# The numpy.any() function returns True if at least one element in the array (or along a specified axis) is True (nonzero).

# 🔹 Syntax
# numpy.any(a, axis=None, out=None, keepdims=False, where=True)

# 🔹 Parameters
# The parameters are exactly the same as numpy.all().

#  i.Check if Any Element Is Nonzero (True)

arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

res = np.any(arr2)
print(res)

[[1 2 3]
 [4 5 6]]
True


In [16]:
# ii Using axis Parameter
arr2 = np.array([[1,2,3],[4,5,6],[7,0,9]])
print(arr2)

print(np.any(arr2,axis=0))
print(np.any(arr2,axis=1))


[[1 2 3]
 [4 5 6]
 [7 0 9]]
[ True  True  True]
[ True  True  True]


In [20]:
# iii.Using keepdims
arr2 = np.array([[1,1,1],[0,0,0]])
print(arr2)

res = np.any(arr2,keepdims=True,axis=1)
print(res)

[[1 1 1]
 [0 0 0]]
[[ True]
 [False]]


In [21]:
# iv.Using where Parameter
arr2d = np.array([[0, 1, 0], 
                  [0, 0, 0]])

mask = np.array([[True, False, True], 
                 [False, True, False]])

result = np.any(arr2d, where=mask)
print(result)  # Output: False

# Extract the elements of arr2d where mask=True:
# [0, 0, 0]

# Position (0,0) → 0 (included)
# Position (0,1) → 1 (ignored because mask=False)
# Position (0,2) → 0 (included)
# Position (1,0) → 0 (ignored)
# Position (1,1) → 0 (included)
# Position (1,2) → 0 (ignored)

# Check if np.any() finds at least one True (nonzero) value:

# The extracted values are [0, 0, 0] → all zeros.
# Since np.any() returns True if at least one value is nonzero, but here all are 0, it returns False.



False


In [23]:
# 35.numpy.cumsum() – Cumulative Sum
# The numpy.cumsum() method computes the cumulative sum of elements along a given axis.

# 🔹 Syntax
# numpy.cumsum(arr, axis=None, dtype=None, out=None)

# 🔹 Parameters
# Parameter	Description
# arr	The input NumPy array.
# axis	The axis along which to perform the cumulative sum.
# dtype	The desired data type for the result.
# out	An optional array to store the result (must be of the same shape as input).


# i.Cumulative Sum Without Axis (Flattened)

arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

print(np.cumsum(arr2))

[[1 2 3]
 [4 5 6]]
[ 1  3  6 10 15 21]


In [24]:
# ii.Cumulative Sum Along axis=0 (Column-wise)

arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)


print(np.cumsum(arr2,axis=0))
# Each column accumulates its values down the rows.


[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [5 7 9]]


In [27]:
# iii.Cumulative Sum Along axis=1 (Row-wise)

arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

print(np.cumsum(arr2,axis=1))
# Each row accumulates its values left to right

[[1 2 3]
 [4 5 6]]
[[ 1  3  6]
 [ 4  9 15]]


In [30]:
# 36.numpy.cumprod() – Cumulative Product
# The numpy.cumprod() method computes the cumulative product of elements along a given axis.

# 🔹 Syntax
# numpy.cumprod(arr, axis=None, dtype=None, out=None)

# 🔹 Parameters
# Parameter	Description
# arr	The input NumPy array.
# axis	The axis along which to perform the cumulative product.
# dtype	The desired data type for the result.
# out	An optional array to store the result (must be of the same shape as input).

# i.Cumulative Product Without Axis (Flattened)

arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

print(np.cumprod(arr2))

# Each column accumulates its product down the rows.

[[1 2 3]
 [4 5 6]]
[  1   2   6  24 120 720]


In [31]:
# ii. Cumulative Product Along axis=0 (Column-wise)

arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

res = np.cumprod(arr2,axis=0)
print(res)
# Each column accumulates its product down the rows.




[[1 2 3]
 [4 5 6]]
[[ 1  2  3]
 [ 4 10 18]]


In [32]:
# iii. Cumulative Product Along axis=1 (Row-wise)

arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

res = np.cumprod(arr2,axis=1)
print(res)
# Each row accumulates its product left to right.


[[1 2 3]
 [4 5 6]]
[[  1   2   6]
 [  4  20 120]]


# Indexing in a 2D NumPy Array

In [33]:
# Indexing is the process of accessing elements from a 2D array using row and column positions.
# In NumPy, a 2D array (also called a matrix) is structured as:

# arr[row, column]
# where:

# row is the index of the row.
# column is the index of the column

In [35]:
arr2 = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr2)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [36]:
print(arr2[0][0])

10


In [38]:
print(arr2[0][1])

20


In [39]:
print(arr2[0][2])

30


In [40]:
print(arr2[1][0])

40


In [41]:
print(arr2[1][1])

50


In [42]:
print(arr2[1][2])

60


In [43]:
print(arr2[2][0])

70


In [44]:
print(arr2[2][1])

80


In [45]:
print(arr2[2][2])

90


In [74]:
# Negative Indexing
print(arr2[-1][-1])

90


In [64]:
print(arr2[-1][-2])

80


In [66]:
print(arr2[-1][-3])

70


In [67]:
print(arr2[-2][-1])

60


In [68]:
print(arr2[-2][-2])

50


In [69]:
print(arr2[-2][-3])

40


In [70]:
print(arr2[-3][-1])

30


In [71]:
print(arr2[-3][-2])

20


In [73]:
print(arr2[-3][-3])

10


In [76]:
# Accessing the Direct Row
# As the column index is not specified it return the entire row.
print(arr2[0])

[10 20 30]


In [77]:
print(arr2[1])

[40 50 60]


In [78]:
print(arr2[2])

[70 80 90]


In [81]:
print(arr2[0,:])

[40 50 60]


In [83]:
print(arr2[1,:])

[40 50 60]


In [84]:
print(arr2[2,:])

[70 80 90]


In [88]:
# Accessing a Whole Column
print(arr2[:,0])
print(type(arr2[:,0]))

[10 40 70]
<class 'numpy.ndarray'>


In [89]:
print(arr2[:,1])

[20 50 80]


In [90]:
print(arr2[:,2])

[30 60 90]


# Slicing in a 2D NumPy Array 

In [91]:
# Slicing in NumPy allows us to extract portions of an array using the syntax:

# array[start:stop:step, start:stop:step]
# The first part (start:stop:step) selects rows.
# The second part (start:stop:step) selects columns.

In [92]:
#  i.Basic Row Slicing

# Extracting Rows
# Slice	Explanation	Output
# arr[0, :]	First row	[10 20 30]
# arr[1, :]	Second row	[40 50 60]
# arr[-1, :]	Last row	[70 80 90]
# arr[:2, :]	First two rows	[[10 20 30], [40 50 60]]
# arr[1:, :]	All rows from index 1 onward	[[40 50 60], [70 80 90]]

In [94]:
# Accessing First Row
print(arr2[0])

[10 20 30]


In [95]:
print(arr2[0,:])

[10 20 30]


In [96]:
# Acesssing Second Row
print(arr2[1])

[40 50 60]


In [97]:
print(arr2[1,:])

[40 50 60]


In [98]:
# Accessing Third Row
print(arr2[2])

[70 80 90]


In [99]:
print(arr2[2,:])

[70 80 90]


In [100]:
# Accessing Last Row
print(arr2[-1])

[70 80 90]


In [101]:
print(arr2[-1,:])

[70 80 90]


In [102]:
# Accessing second last Row
print(arr2[-2])

[40 50 60]


In [104]:
print(arr2[-2,:])

[40 50 60]


In [106]:
# Accessing Third last Row
print(arr2[-3])

[10 20 30]


In [107]:
print(arr2[-3,:])

[10 20 30]


In [109]:
# 2. Column Slicing
# Extracting Columns
# Slice	Explanation	Output
# arr[:, 0]	First column	[10 40 70]
# arr[:, -1]	Last column	[30 60 90]
# arr[:, 1:3]	Last two columns	[[20 30], [50 60], [80 90]]

In [111]:
# Accessing the First Column
print(arr2[:,0])

[10 40 70]


In [121]:
# Accessing the Second Column
print(arr2[:,1])

[20 50 80]


In [122]:
# Accessing the third column
print(arr2[:,2])

[30 60 90]


In [124]:
# Extracting first two rows 

print(arr2[:2,:])

[[10 20 30]
 [40 50 60]]


In [125]:
print(arr2[:2])

[[10 20 30]
 [40 50 60]]


In [127]:
# Extracting Last two rows
print(arr2[-2:,:])

[[40 50 60]
 [70 80 90]]


In [131]:
print(arr2[-2:])

[[40 50 60]
 [70 80 90]]


In [134]:
# Extracting first two columns
print(arr2[:,:2])

[[10 20]
 [40 50]
 [70 80]]


In [136]:
# Extracting last two columns
print(arr2[:,-2:])

[[20 30]
 [50 60]
 [80 90]]


In [137]:
#  How do you access the element at row index 1 and column index 2 in a 2D array?
print(arr2[1][2])

60


In [138]:
# How do you retrieve the entire first row of a 2D array
print(arr2[0])

[10 20 30]


In [139]:
# How do you retrieve the entire second column of a 2D array
print(arr2[1])

[40 50 60]


In [141]:
# How do you modify a specific element, say arr[1,1] = 99, in a 2D array
arr2[1,1] = 99
print(arr2)

[[10 20 30]
 [40 99 60]
 [70 80 90]]


In [143]:
# How do you extract multiple specific rows, such as the 1st and 3rd rows
print(arr2[0::2])

[[10 20 30]
 [70 80 90]]


In [144]:
# How do you extract multiple specific columns, such as the 1st and 3rd columns
print(arr2[:,::2])

[[10 30]
 [40 60]
 [70 90]]


In [145]:
# What does arr[:, :] return when applied to a 2D array
print(arr2[:,:])

[[10 20 30]
 [40 99 60]
 [70 80 90]]


In [146]:
# How do you swap the first and last rows of a 2D array using indexing
print("Before Swap",arr2)
arr2[[0,-1]] = arr2[[-1,0]]
print("After Swap",arr2)

# Explanation:
# arr[0] refers to the first row.
# arr[-1] refers to the last row.
# arr[[0, -1]] = arr[[-1, 0]] swaps them using fancy indexing.


Before Swap [[10 20 30]
 [40 99 60]
 [70 80 90]]
After Swap [[70 80 90]
 [40 99 60]
 [10 20 30]]


In [150]:
# How do you reverse all the columns of a 2D array

arr2 = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])
print(arr2[:,::-1])

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [154]:
# Reverse the entire array
arr2 = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])
print(arr2[::-1,::-1])

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [155]:
# How do you access the last row of a 2D array using negative indexing
print(arr2[-2:])

[[4 5 6]
 [7 8 9]]


In [156]:
# How do you access the last column of a 2D array using negative indexing
print(arr2[:,-1:])

[[3]
 [6]
 [9]]


In [157]:
# What does arr[-2, -1] return in a 2D array
print(arr2[-2,-1])

6


In [159]:
# How do you extract the last two rows from a 2D array?
print(arr2[1:])

[[4 5 6]
 [7 8 9]]


In [160]:
# How do you extract the last two columns from a 2D array?
print(arr2[:,1:])

[[2 3]
 [5 6]
 [8 9]]


In [161]:
#  How do you extract the top-left 2×2 subarray from a 3×3 array?
print(arr2[:2,:2])

[[1 2]
 [4 5]]


In [162]:
# How do you extract every second row from a 2D array?

arr2 = np.array([[1,2,3,4],[5,6,7,8],[10,11,12,13],[14,15,16,17]])
print(arr2[::2])

[[ 1  2  3  4]
 [10 11 12 13]]


In [163]:
# How do you extract every second column from a 2D array?
print(arr2[::,::2])

[[ 1  3]
 [ 5  7]
 [10 12]
 [14 16]]


In [164]:
# What does arr[::2, ::2] return?
print(arr2[::2,::2])

[[ 1  3]
 [10 12]]


In [166]:
# How do you extract the bottom-right corner of a 2D array?


arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
print(arr2[1::,1::])

[[5 6]
 [8 9]]


In [5]:
# How do you extract all elements greater than 10 in a 2D array
mask = arr2>10
print(mask)

# Return the 1D Array containing the elements that matches the mask value.
print(arr2[mask])

[[False  True  True]
 [ True  True  True]]
[20 30 40 50 60]


In [8]:
# How do you extract all even numbers from a 2D array?
con = arr2%2==0
print(con)

print(arr2[con])

[[ True  True  True]
 [ True  True  True]]
[10 20 30 40 50 60]


In [9]:
# What does arr[arr % 2 == 0] return
print(arr2[arr2%2==0])

[10 20 30 40 50 60]


In [15]:
# How do you replace all elements less than 5 with zero?

import numpy as np

arr2 = np.array([[3, 5, 7], 
                [1, 9, 4], 
                [6, 2, 8]])

print("Original Array",arr2)
arr2[arr2<5] = 0
print("After Replacing with Zeros",arr2)

Original Array [[3 5 7]
 [1 9 4]
 [6 2 8]]
After Replacing with Zeros [[0 5 7]
 [0 9 0]
 [6 0 8]]


In [18]:
# How do you count the number of elements greater than 50 in a 2D array

arr2 = np.array([[10,20,30],[40,50,60],[60,70,80]])

count = np.sum(arr2>50)
print("The no. of elements greater than 50 is",count)


The no. of elements greater than 50 is 4


In [19]:
# How do you extract non-consecutive rows, like rows 0 and 2?

arr2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(arr2[::2,::])

[[ 1  2  3]
 [ 7  8  9]
 [13 14 15]]


In [20]:
# How do you extract non-consecutive columns, like columns 1 and 3?

arr2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(arr2[::,::2])

[[ 1  3]
 [ 4  6]
 [ 7  9]
 [10 12]
 [13 15]]


In [21]:
# What does arr[[0, 2], :] return?
print(arr2[[0,2],:])

# Explanation of arr[[0, 2], :]
# [0, 2] inside arr[] → Selects row indices 0 and 2.
# : (colon) inside arr[] → Selects all columns.
# The result is a submatrix containing rows 0 and 2.


[[1 2 3]
 [7 8 9]]


In [33]:
#  How do you select specific rows and columns at the same time
print(arr2[[0,2],:][:,[1,2]])

[[2 3]
 [8 9]]


In [43]:
# How do you extract diagonal elements using indexing?
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)
print()
print("Diagonals Using diagonal method",arr2.diagonal())
print()



[[1 2 3]
 [4 5 6]
 [7 8 9]]

Diagonals Using diagonal method [1 5 9]

Diagonals using range method [1 5 9]


In [44]:
print("Diagonals using range method",arr2[range(arr2.shape[0]),range(arr2.shape[0])])
# Step-by-Step Explanation:
# Understanding arr2.shape

# arr2.shape
# This returns (3, 3), meaning there are 3 rows and 3 columns.

# Generating Index Ranges:

# range(arr2.shape[0])  # range(3) → [0, 1, 2]
# range(arr2.shape[1])  # range(3) → [0, 1, 2]
# These represent row and column indices of the diagonal elements.

# Fancy Indexing Usage:

# arr2[[0, 1, 2], [0, 1, 2]]
# This selects elements at:

# (0,0) → 1
# (1,1) → 5
# (2,2) → 9

# Final Extraction:

# [1 5 9]
# The diagonal elements [1, 5, 9] are extracted.

Diagonals using range method [1 5 9]


In [45]:
# Using np.trace() (For Sum of Diagonal)
# If you just need the sum of diagonal elements:

print(np.trace(arr2))

15


In [53]:
# Extracting the Other (Anti) Diagonal
# If you want to extract the anti-diagonal (bottrom-left to top-right):
res = np.fliplr(arr2).diagonal()
print(res)

# np.fliplr(arr2) flips the array left to right, and then diagonal() extracts the diagonal.



[3 5 7]


# Rearranging the rows 

In [58]:
# Method 1: Using Indexing
# You can specify the desired row order using row indices.

arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Original Array',arr2)

print('New Changed Array',arr2[[2,0,1]])

# How It Works:
# arr2[[2, 0, 1]] → selects rows in the order of indices [2, 0, 1]
# This does not modify the original array; it creates a new array with the reordered rows.
# The column order remains unchanged.


Original Array [[1 2 3]
 [4 5 6]
 [7 8 9]]
New Changed Array [[7 8 9]
 [1 2 3]
 [4 5 6]]


In [65]:
print(arr2[:,[2,0,1]])

[[3 1 2]
 [6 4 5]
 [9 7 8]]


In [70]:
# Method 2: Using numpy.roll()
# Shifts all rows circularly by a given number of positions.
# The np.roll() function shifts elements in an array circularly along a specified axis. 
# When applied to a 2D array with axis=0, it rolls the rows up or down.


arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Original Array',arr2)

# Shift 1 means move all the rows down by 1.
rolled_arr = np.roll(arr2,axis=0,shift=1)
print("Rolled Array down by 1",rolled_arr)


# Shift -1 means move all the rows up by 1.
rolled_arr = np.roll(arr2,axis=0,shift=-1)
print("Rolled Array up by 1",rolled_arr)


# Parameter	Effect
# shift=1	Rolls rows down (last row moves to the first)
# shift=-1	Rolls rows up (first row moves to the last)
# axis=0	Specifies row-wise shifting (vertical)

Original Array [[1 2 3]
 [4 5 6]
 [7 8 9]]
Rolled Array down by 1 [[7 8 9]
 [1 2 3]
 [4 5 6]]
Rolled Array up by 1 [[4 5 6]
 [7 8 9]
 [1 2 3]]


In [71]:
# Using numpy.flip()
# Reverses the order of rows.

arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Original Array',arr2)

res = np.flip(arr2,axis=0)
print("Flipped Array",res)

Original Array [[1 2 3]
 [4 5 6]
 [7 8 9]]
Flipped Array [[7 8 9]
 [4 5 6]
 [1 2 3]]
