# What is a 3D Array



In [2]:
# A 3D NumPy array is an extension of a 2D array, where elements are arranged in multiple matrices (2D arrays) stacked together, forming a three-dimensional structure.
# It can be thought of as a collection of 2D arrays along a third axis.

In [3]:
# Definition of a 3D Array

# A 3D array in NumPy is represented as:
# arr[depth,row,column]

# where:
# Depth (Axis=0): Represents different 2D matrices stacked along the first axis.
# Rows (Axis=1): Represents the number of rows in each 2D matrix.
# Columns (Axis=2): Represents the number of columns in each 2D matrix.

In [2]:
# Creating the 3D Array.

import numpy as np
arr3 = np.array([[[1,2,3]],[[4,5,6]]])
print(arr3)
print(type(arr3))
print(arr3.shape)

[[[1 2 3]]

 [[4 5 6]]]
<class 'numpy.ndarray'>
(2, 1, 3)


# Properities of 3D Array

In [8]:
# A 3D NumPy array has several properties that help us understand its structure, shape, and behavior.
# Below is a detailed explanation of all the key properties.

In [15]:
# 1. shape – Dimensions of the Array
# The shape property returns the number of elements along each axis in the form of a tuple.

# 🔹 Definition:
# arr.shape  # Returns (depth, rows, columns)
# Depth (axis=0) → Number of stacked 2D arrays (matrices).
# Rows (axis=1) → Number of rows in each matrix.
# Columns (axis=2) → Number of columns in each matrix.

arr3 = np.array([
    [[1,2,3],[4,5,6]],
    [[4,5,6],[1,2,3]]
])
print(arr3)
print("The Shape of the array is",arr3.shape)
# Explanation: There are 2 matrices, each with 2 rows and 3 columns.

[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [1 2 3]]]
The Shape of the array is (2, 2, 3)


In [14]:
# 2. ndim – Number of Dimensions
# The ndim property returns the number of dimensions in the array.

# 🔹 Definition:
# arr.ndim  # Returns the number of dimensions

arr2 = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])
print(arr2)
print("The Dimension of the array is",arr2.ndim)
# The array has 3 dimensions (depth, rows, columns).

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
The Dimension of the array is 3


In [16]:
# 3. size – Total Number of Elements
# The size property returns the total number of elements in the array.

# 🔹 Definition:
# arr.size  # Returns total number of elements

arr3 = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])
print(arr3)
print("The no. of elements in the array is",arr3.size)
# There are 2 × 2 × 3 = 12 elements.

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
The no. of elements in the array is 12


In [17]:
#  4. dtype – Data Type of Elements
# The dtype property returns the data type of the elements in the array.

# 🔹 Definition:
# arr.dtype  # Returns data type of elements

arr3 = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])

print(arr3)
print("The dtype of elements of the array is",arr3.dtype)
# the elements in arr3d are integers (int32 on most systems).

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
The dtype of elements of the array is int32


In [18]:
# 5. itemsize – Size of Each Element in Bytes
# The itemsize property returns the memory size (in bytes) of each element in the array.

# Definition:
# arr.itemsize # Returns size of one element in bytes

arr3 = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])

print(arr3)
print("Size of one element in byte is",arr3.itemsize)

# Explanation:

# If int32, each element takes 4 bytes.
# If int64, each element takes 8 bytes.


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Size of one element in byte is 4


In [20]:
# 6. nbytes – Total Memory Usage of the Array
# The nbytes property returns the total memory occupied by the entire array.

arr3 = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])
print(arr3)
print("Total size of the array in bytes is",arr3.nbytes)

# The array has 12 elements, and each takes 4 bytes → 12 × 4 = 48 bytes.

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Total size of the array in bytes is 48


In [25]:
# 7. T – Transpose of a 3D Array
# The T property returns the transpose of the array, swapping its axes.

# 🔹 Definition:
# arr.T  # Returns a transposed view of the array

arr3 = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])
print("Original Array")
print(arr3)
print("Tranposed Array")
print(arr3.T)
print(arr3.T.shape)

Original Array
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Tranposed Array
[[[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]

 [[ 3  9]
  [ 6 12]]]
(3, 2, 2)


In [27]:
# 8.flat- Flatten MultiDimensional array into 1D
# The flat property return the iterator loop throught element efficiently.

arr3 = np.array([
    [[10,20,30],[40,50,60]],
    [[70,80,90],[110,110,120]]
])
print("Original Array")
print(arr3)

for i in arr3.flat:
    print(i,end=' ')

Original Array
[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [110 110 120]]]
10 20 30 40 50 60 70 80 90 110 110 120 

# Indexing in a 3D NumPy Array

In [1]:
# Indexing in a 3D array follows the [depth, row, column] structure.
# This allows us to access, modify, and extract elements or sub-arrays in different ways.

In [2]:
# Understanding 3D Array Structure
# A 3D array is essentially a collection of stacked 2D arrays (matrices).
# Each element is accessed using three indices:

# First index (Depth - axis=0) → Selects which 2D matrix to access.
# Second index (Row - axis=1) → Selects which row within the chosen matrix.
# Third index (Column - axis=2) → Selects which column within the row.

In [5]:
arr3 = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]],
    [[13,14,15],[16,17,18]]
])
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [26]:
# Positive Indexing 
print(arr3[0,0,0])

1


In [27]:
print(arr3[0,0,1])

2


In [28]:
print(arr3[0,0,2])

3


In [29]:
print(arr3[0,1,0])

4


In [30]:
print(arr3[0,1,1])

5


In [31]:
print(arr3[0,1,2])

6


In [32]:
print(arr3[1,0,0])

7


In [33]:
print(arr3[1,0,1])

8


In [34]:
print(arr3[1,0,2])

9


In [35]:
print(arr3[1,1,0])

10


In [36]:
print(arr3[1,1,1])

11


In [37]:
print(arr3[1,1,2])

12


In [38]:
print(arr3[2,0,0])

13


In [39]:
print(arr3[2,0,1])

14


In [40]:
print(arr3[2,0,2])

15


In [41]:
print(arr3[2,1,0])

16


In [42]:
print(arr3[2,1,1])

17


In [43]:
print(arr3[2,1,2])

18


In [44]:
# Negative Indexing
arr3 = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]],
    [[13,14,15],[16,17,18]]
])
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [45]:
print(arr3[-1,-1,-1])

18


In [47]:
print(arr3[-1,-1,-2])

17


In [48]:
print(arr3[-1,-1,-3])

16


In [49]:
print(arr3[-1,-2,-1])

15


In [50]:
print(arr3[-1,-2,-2])

14


In [51]:
print(arr3[-1,-2,-3])

13


In [52]:
print(arr3[-2,-1,-1])

12


In [53]:
print(arr3[-2,-1,-2])

11


In [54]:
print(arr3[-2,-1,-3])

10


In [55]:
print(arr3[-2,-2,-1])

9


In [56]:
print(arr3[-2,-2,-2])

8


In [57]:
print(arr3[-2,-2,-3])

7


In [58]:
print(arr3[-3,-1,-1])

6


In [59]:
print(arr3[-3,-1,-2])

5


In [60]:
print(arr3[-3,-1,-3])

4


In [61]:
print(arr3[-3,-2,-1])

3


In [62]:
print(arr3[-3,-2,-2])

2


In [63]:
print(arr3[-3,-2,-3])

1


# Accessing a Full 2D Slice (Depth Selection)

In [64]:
arr3 = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]],
    [[13,14,15],[16,17,18]]
])
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [65]:
print(arr3[0])

[[1 2 3]
 [4 5 6]]


In [66]:
print(arr3[1])

[[ 7  8  9]
 [10 11 12]]


In [67]:
print(arr3[2])

[[13 14 15]
 [16 17 18]]


# Slicing in a 3D NumPy Array – Detailed Explanation

In [71]:
# Slicing in a 3D array allows you to extract specific subarrays, depth slices, rows, and columns using the format:

# arr[start:stop:step, start:stop:step, start:stop:step]
# Here’s how slicing works in a 3D array:

# First index (Depth - axis=0) → Slices across depth layers (matrices).
# Second index (Row - axis=1) → Slices rows from each selected depth layer.
# Third index (Column - axis=2) → Slices columns from each selected row.

In [75]:
arr3 = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]],
    [[13,14,15],[16,17,18]]
])
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


# Accessing a Single Row Across Depths

In [ ]:
# To extract a specific row from all depth layers:

In [81]:
arr3 = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]],
    [[13,14,15],[16,17,18]]
])
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [82]:
# First Row of all the depths
print(arr3[:,0,:])

[[ 1  2  3]
 [ 7  8  9]
 [13 14 15]]


In [83]:
# Second Row of all the Depths
print(arr3[:,1,:])

[[ 4  5  6]
 [10 11 12]
 [16 17 18]]


# Accessing a Single Column Across Depths

In [84]:
# To extract a specific column from all depth layers:

In [85]:
arr3 = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]],
    [[13,14,15],[16,17,18]]
])
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [86]:
# first column of all the depths
print(arr3[:,:,0])

[[ 1  4]
 [ 7 10]
 [13 16]]


In [87]:
# Second column of all the depths
print(arr3[:,:,1])

[[ 2  5]
 [ 8 11]
 [14 17]]


In [88]:
# third column of all the depths
print(arr3[:,:,2])

[[ 3  6]
 [ 9 12]
 [15 18]]


# Extracting a Full Row from a Specific Depth

In [ ]:
# To select a specific row from a specific depth:

In [89]:
arr3 = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]],
    [[13,14,15],[16,17,18]]
])
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [90]:
# Selecting the first Row from Zero depth
print(arr3[0,0,:])

[1 2 3]


In [91]:
# Selecting the Second Row from Zero depth
print(arr3[0,1,:])

[4 5 6]


In [92]:
# Selecting the first Row from First depth
print(arr3[1,0,:])

[7 8 9]


In [93]:
# Selecting the Second Row from First depth
print(arr3[1,1,:])

[10 11 12]


In [94]:
# Selecting the First Row from Second depth
print(arr3[2,0,:])

[13 14 15]


In [95]:
# Selecting the Second Row from Second depth
print(arr3[2,1:])

[[16 17 18]]


# Extracting a Full Column from a Specific Depth

In [96]:
# To select a specific column from a specific depth:

In [97]:
arr3 = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]],
    [[13,14,15],[16,17,18]]
])
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [98]:
# Select the first Column from Zero depth
print(arr3[0,:,0])

[1 4]


In [100]:
# Select the Second Column from Zero depth
print(arr3[0,:,1])

[2 5]


In [101]:
# Select the third Column from Zero depth
print(arr3[0,:,2])

[3 6]


In [102]:
# Select the first Column from first depth
print(arr3[1,:,0])

[ 7 10]


In [103]:
# Select the Second Column from first depth
print(arr3[1,:,1])

[ 8 11]


In [104]:
# Select the Third Column from first depth
print(arr3[1,:,2])

[ 9 12]


In [105]:
# Select the first Column from Second depth
print(arr3[2,:,0])

[13 16]


In [106]:
# Select the Second Column from Second depth
print(arr3[2,:,1])

[14 17]


In [107]:
# Select the Third Column from Second depth
print(arr3[2,:,2])

[15 18]


# Extracting a Diagonal (Across Depths)

In [108]:
# To extract diagonal elements across all depths:

arr3 = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]],
    [[13,14,15],[16,17,18]]
])
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [109]:
print(arr3[:,0,0])

[ 1  7 13]


In [114]:
arr3 = np.array([
    [[1,2,3]],
    [[7,8,9]],
    [[13,14,15]]
])
print(arr3)

[[[ 1  2  3]]

 [[ 7  8  9]]

 [[13 14 15]]]


In [116]:
# Let's analyze how .diagonal() works:

# .diagonal() works on the last two dimensions ((rows, columns)) of the array.
# It extracts diagonal elements where row index = column index within these last two dimensions.
# However, your array only has one row per depth, meaning that the diagonal extraction isn't happening in the usual way. 
# Instead, NumPy ignores the missing rows and still extracts one element per depth.

print(arr3.diagonal())

[[1]
 [2]
 [3]]


# Reversing a 3D Array Using Slicing

In [117]:
arr3 = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]],
    [[13,14,15],[16,17,18]]
])
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [121]:
# Reverses depth layers.
print(arr3[::-1])

[[[13 14 15]
  [16 17 18]]

 [[ 7  8  9]
  [10 11 12]]

 [[ 1  2  3]
  [ 4  5  6]]]


In [122]:
# Reversing Row Order
print(arr3[:,:,::-1])

[[[ 3  2  1]
  [ 6  5  4]]

 [[ 9  8  7]
  [12 11 10]]

 [[15 14 13]
  [18 17 16]]]


In [123]:
# Reversing Column Order
print(arr3[:,::-1,:])

[[[ 4  5  6]
  [ 1  2  3]]

 [[10 11 12]
  [ 7  8  9]]

 [[16 17 18]
  [13 14 15]]]


In [124]:
arr3 = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]],
    [[13,14,15],[16,17,18]]
])
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [126]:
# 1️⃣ How do you access the element at depth index 1, row index 1, and column index 0 in a 3D array arr3?
print(arr3[1,1,0])

10


In [134]:
# 3️⃣ How do you select an entire row from depth index 0 and row index 1?
print(arr3[0,1,:])

[4 5 6]


In [136]:
# 4️⃣ How do you select an entire column from depth index 2 and column index 1?
print(arr3[2,:,1])

[14 17]


In [137]:
# 5️⃣ What does arr3[:, 1, 2] return?
print(arr3[:,1,2])

[ 6 12 18]


In [142]:
# 6️⃣ How do you extract the first element from each depth in a 3D array?
print(arr3[:,0,0])

[ 1  7 13]


In [143]:
# 7️⃣ What happens if you use negative indexing in a 3D array?
print(arr3[-1,-1,-1])

18


In [144]:
# 8️⃣ How do you extract all elements from the first two depths in a 3D array?
print(arr3[:2,:,:])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [145]:
# 9️⃣ What does arr3[:, :, 1] return?
print(arr3[:,:,1])

[[ 2  5]
 [ 8 11]
 [14 17]]


In [147]:
# 🔟 How do you extract every second row from a 3D array?
print(arr3[:,1,:])

[[ 4  5  6]
 [10 11 12]
 [16 17 18]]


In [149]:
# 1️⃣1️⃣ What does arr3[1:, 0, :] return?
print(arr3[1:, 0, :])

[[ 7  8  9]
 [13 14 15]]


In [151]:
# 1️⃣2️⃣ How do you reverse the order of depths in a 3D array?
print(arr3[::-1,:,:])

[[[13 14 15]
  [16 17 18]]

 [[ 7  8  9]
  [10 11 12]]

 [[ 1  2  3]
  [ 4  5  6]]]


In [152]:
# 1️⃣3️⃣ How do you reverse the order of rows in a 3D array?
print(arr3[:,:,::-1])

[[[ 3  2  1]
  [ 6  5  4]]

 [[ 9  8  7]
  [12 11 10]]

 [[15 14 13]
  [18 17 16]]]


In [153]:
# 1️⃣4️⃣ How do you reverse the order of columns in a 3D array?
print(arr3[:,::-1,:])

[[[ 4  5  6]
  [ 1  2  3]]

 [[10 11 12]
  [ 7  8  9]]

 [[16 17 18]
  [13 14 15]]]


In [155]:
# 1️⃣5️⃣ What does arr3[::-1, ::-1, ::-1] do?
print(arr3[::-1,::-1,::-1])

[[[18 17 16]
  [15 14 13]]

 [[12 11 10]
  [ 9  8  7]]

 [[ 6  5  4]
  [ 3  2  1]]]


In [162]:
# 1️⃣7️⃣ How do you swap two depths in a 3D array using slicing?
arr3[[0,2]] = arr3[[2,0]]
print(arr3)

# If we have a (3,2,3) array, swapping the first (depth index 0) and last (depth index -1 or 2) depth:

# arr3[[0, 2]] = arr3[[2, 0]]
# This swaps the first and last depth while keeping rows and columns unchanged.

[[[13 14 15]
  [16 17 18]]

 [[ 7  8  9]
  [10 11 12]]

 [[ 1  2  3]
  [ 4  5  6]]]


# Methods of 3D Array

# 1 astype() method 

In [ ]:
# The astype() method in NumPy is used to convert the data type of a NumPy array to a specified type.

# Syntax:
# array.astype(dtype, order='K', casting='unsafe', subok=True, copy=True)

# Parameter	Description
# 1.dtype	The target data type to which the array should be converted. Example: np.int32, np.float64, np.bool_, np.complex_, 
# 2.order	Specifies the memory layout.
# Options:
# - 'C' (C-style row-major order)
# - 'F' (Fortran-style column-major order)
# - 'A' (Any order; defaults to existing)
# - 'K' (Keeps existing order)
# casting	Defines how strict the conversion should be. Options:
# - 'no' (Disallows casting)
# - 'equiv' (Only equivalent types allowed)
# - 'safe' (Only safe conversions, e.g., int32 → float64 but not float64 → int32)
# - 'same_kind' (Allows conversions within similar types)
# - 'unsafe' (Allows all conversions, even data loss)
# subok	If True, subclasses are passed through; if False, returned array is forced to be a base NumPy array.
# copy	If True, always returns a new array. If False, a new array is returned only if necessary (e.g., if the type actually changes).

In [9]:
import numpy as np
arr = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])
print(arr)
print(arr.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


In [15]:
new_arr = arr.astype(float)
print(new_arr)
print(new_arr.dtype)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
float64


# 2.copy method

In [16]:
# The copy() method in NumPy is used to create a new independent copy of an existing array. 
# Changes made to the copied array do not affect the original array.

# Syntax:
# array.copy(order='K')

# Parameter	Description
# order	Specifies the memory layout of the copied array. Options:
# - 'C' → Row-major order (default)
# - 'F' → Column-major order
# - 'A' → Keeps existing order (C or F)
# - 'K' → Tries to preserve original order as much as possible

# 🔹 Note:
# If order='C', the new array follows C-contiguous memory layout (row-wise storage).
# If order='F', the new array follows Fortran-contiguous memory layout (column-wise storage).
# If order='K', it keeps the original order of elements as much as possible.

In [22]:
arr = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])
new_arr = arr.copy()

arr[0][0][0] = 1000
print("After Changes")
print(new_arr)

print()

print("Original Array")
print(arr)

After Changes
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Original Array
[[[1000    2    3]
  [   4    5    6]]

 [[   7    8    9]
  [  10   11   12]]]


# 3.view() Method 

In [24]:
# The view() method in NumPy creates a new view of an array without copying the data. 
# This means the new array shares the same memory as the original array, so changes to one affect the other.

# Syntax:
# array.view(dtype=None)

# Parameter	Description
# dtype	(Optional) Specifies a different data type for the view (e.g., float32, int8). 
# If None, it keeps the original dtype.

In [25]:
arr = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])
new_view = arr.view()

new_view[0][0][0] = 1000
print("After Changes")
print(new_view)

print()

print("Original Array")
print(arr)

After Changes
[[[1000    2    3]
  [   4    5    6]]

 [[   7    8    9]
  [  10   11   12]]]

Original Array
[[[1000    2    3]
  [   4    5    6]]

 [[   7    8    9]
  [  10   11   12]]]


# 4. reshape() Method

In [26]:
# The reshape() method in NumPy changes the shape of an array without changing its data. 
# It returns a new view (or a copy in some cases) of the original array with a different shape.

# Syntax:
# array.reshape(new_shape, order='C')

# Parameter	Description
# new_shape	A tuple that specifies the new dimensions of the array. The total number of elements must remain the same.
# order	(Optional) Determines how elements are read and placed in the new shape. Possible values:
# 'C' → Row-major order (C-style, default)
# 'F' → Column-major order (Fortran-style)
# 'A' → Fortran-like order if the original array is Fortran-contiguous; otherwise, C-order
# 'K' → Keeps the elements in memory order

# Return Type:
# Returns a new array with the specified shape.
# If possible, it returns a view (shares memory with the original).
# Otherwise, it returns a copy (independent memory).

In [28]:
# 1️⃣ Reshaping a 3D Array
arr = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])

new_arr = arr.reshape(3,2,2)
print("Original Array")
print(arr)
print()

print("Reshaped Array")
print(new_arr)


# Explanation:
# The original shape (2, 2, 3) → (3, 2, 2).
# The total elements (2×2×3 = 3×2×2 = 12) remain the same.

Original Array
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Reshaped Array
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [29]:
# 2️⃣ Reshaping with -1 (Automatic Dimension Calculation)
arr = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])
new_shape = arr.reshape(3,-1,2)
print(new_shape)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [30]:
# 3️⃣ Reshaping with Fortran Order ('F')
new_arr= arr.reshape((3, 2, 2), order='F')  
print(new_arr)


[[[ 1  5]
  [10  9]]

 [[ 7 11]
  [ 2  6]]

 [[ 4  3]
  [ 8 12]]]


In [31]:
# 4️⃣ Reshaping a 3D Array into a 2D Array
arr2d = arr.reshape((4, 3))  # Flattening depth into rows
print(arr2d)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [32]:
# 5️⃣ Reshaping a 3D Array into a 1D Array

arr1d = arr.reshape(-1)
print(arr1d)

# Explanation:
# reshape(-1) flattens the entire array into 1D.

[ 1  2  3  4  5  6  7  8  9 10 11 12]


# 5.transpose() Method

In [33]:
# The transpose() method rearranges the axes (dimensions) of a NumPy array, effectively changing how elements are indexed along different axes.

# Syntax:
    
# array.transpose(axes=None)

# Parameter	Description
# axes	(Optional) A tuple specifying the new order of axes. If None, the dimensions are reversed ([::-1]).
# If no axes are given, default is reversing the order of dimensions.
# The tuple must contain all the axes exactly once.

# Return Type:
# Returns a view of the array with reordered axes.
# If a copy is needed, use .copy() after transposing.

In [36]:
# 1️⃣ Default Transpose (Reverse Axes)
arr = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])
new_arr = arr.transpose()
print(new_arr)


# Explanation:
# The shape changes from (2, 2, 3) → (3, 2, 2).
# Default behavior reverses the axes order.

[[[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]

 [[ 3  9]
  [ 6 12]]]


# 6.flatten() Method

In [1]:
# The flatten() method in NumPy is used to convert a multi-dimensional array (including 3D arrays) into a 1D array.

# Syntax:
# flattened_array = arr3d.flatten(order='C')

# Parameters:
# Parameter	Description	Default
# order	Determines how elements are read from the 3D array (row-wise, column-wise, etc.)	'C'


# Return Type
# Returns a new 1D NumPy array with all elements from the 3D array.
# The original array remains unchanged (unlike ravel(), which may return a view).

In [14]:
arr = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])
flat_arr = arr.flatten(order='C')
print("1D array")
print(flat_arr)
print()
print("3D array")
print(arr)

1D array
[ 1  2  3  4  5  6  7  8  9 10 11 12]

3D array
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [15]:
arr = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])
flat_arr = arr.flatten(order='F')
print("1D array")
print(flat_arr)
print()
print("3D array")
print(arr)

1D array
[ 1  7  4 10  2  8  5 11  3  9  6 12]

3D array
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


# 7.ravel() method

In [16]:
# ravel() Method
# The ravel() method is used to return a 1D view (or a copy) of a multi-dimensional array, including 3D arrays.

# Syntax:
# flattened_array = arr3d.ravel(order='C')

# Parameters:
# order	Determines how elements are read from the 3D array (row-wise, column-wise, etc.)	'C'

# Order Options:
# 1️⃣ 'C' (Row-Major Order - C-style) [DEFAULT]
# Reads elements row-wise, moving across columns first.
# Follows the memory layout used in C programming.

# 2️⃣ 'F' (Column-Major Order - Fortran-style)
# Reads elements column-wise, moving down rows first.
# Useful for accessing elements in Fortran-style storage.

# 3️⃣ 'A' (Automatic Order)
# Uses 'F' if the array is Fortran-contiguous, otherwise 'C'.

# 4️⃣ 'K' (Memory Order - Preserve Layout)
# Preserves the memory layout of the original array.


# Return Type
# Returns a 1D NumPy array containing all elements of the original 3D array.
# Returns a view (if possible), or a copy if needed.

In [25]:
arr = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])
ravel_arr = arr.ravel(order='C')
print("1D array")
print(flat_arr)
print()
print("3D array")
print(arr)

print()
ravel_arr[0] = 1000
print("After Changes")
print(ravel_arr)
print()
print("Original Array")
print(arr)

1D array
[ 1  2  3  4  5  6  7  8  9 10 11 12]

3D array
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

After Changes
[1000    2    3    4    5    6    7    8    9   10   11   12]

Original Array
[[[1000    2    3]
  [   4    5    6]]

 [[   7    8    9]
  [  10   11   12]]]


# 8.sum() method

In [26]:
# sum() Method 
# The sum() method computes the sum of array elements over a specified axis. In a 3D array, we can control how summation happens across different dimensions.

# 🔹 Syntax:
# numpy.sum(arr, axis=None, dtype=None, out=None, keepdims=False, initial=0, where=True)

# 🔹 Parameters:
# axis	Specifies the axis along which to sum. Default is None (sum all elements).
# dtype	The data type for the sum. Default is inferred from arr.
# out	An optional output array to store the result. Must be same shape as expected output.
# keepdims	If True, retains reduced dimensions with size 1 instead of collapsing them.
# initial	The starting value for summation. Default is 0.
# where	A boolean mask that specifies which elements to include in the sum.

In [ ]:
# Summary Table
# Parameter	Description
# axis=0	Sum across depths (shape reduces to (rows, cols)).
# axis=1	Sum across rows (shape reduces to (depths, cols)).
# axis=2	Sum across columns (shape reduces to (depths, rows)).
# dtype	Ensures a specific data type for the result.
# out	Stores result in an existing array.
# keepdims=True	Keeps the reduced dimension as 1.
# initial	Adds a starting value to the sum.
# where	Applies a condition (Boolean mask).

In [27]:
arr = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [28]:
#  1: Sum All Elements in a 3D Array
print(arr.sum())
#  Adds all numbers in the 3D array.

78


In [29]:
#  2: Sum Along an Axis
# Sum Along axis=0 (Depth-Wise)
print(arr.sum(axis=0))

# Adds elements across different depths (0th axis).
# arr3d.shape = (3, 2, 3) → result.shape = (2, 3)

[[ 8 10 12]
 [14 16 18]]


In [30]:
# Sum Along axis=1 (Row-Wise)
print(arr.sum(axis=1))
# Adds elements across rows within each depth.

[[ 5  7  9]
 [17 19 21]]


In [31]:
# Sum Along axis=2 (Column-Wise)
print(arr.sum(axis=2))
# Adds elements across columns within each row and depth.

[[ 6 15]
 [24 33]]


In [32]:
# 3: Using dtype to Control Precision
print(arr.sum(dtype=np.float64))

78.0


In [33]:
# 4: Using keepdims=True
print(arr.sum(keepdims=True))

[[[78]]]


In [34]:
# 5: Using initial Parameter
print(arr.sum(initial=100))
# Starts summation with 100, so 78 + 100 = 178

178


In [35]:
# 6: Using where Parameter
mask = arr<5
print(arr.sum(where=mask))

10


# 9.max() Method 

In [36]:
# The max() method in NumPy returns the maximum value along a specified axis in a 3D array.

# 🔹 Syntax:
# numpy.max(arr, axis=None, out=None, keepdims=False, initial=None, where=True)

# 🔹 Parameters:
# Parameter	Description
# axis	Specifies the axis along which to find the maximum. Default is None (finds max of all elements).
# out	An optional output array to store the result. Must have the same shape as expected output.
# keepdims	If True, retains reduced dimensions with size 1 instead of collapsing them.
# initial	The starting value for comparison. If specified, max will compare against this value.
# where	A boolean mask specifying which elements to consider in the maximum calculation.

In [37]:
arr = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [38]:
# 1: Find the Maximum in a 3D Array
print(arr.max())

12


In [39]:
# 2: Find Maximum Along Different Axes

# 1️⃣ Find Maximum Along axis=0 (Depth-Wise)
print(arr.max(axis=0))

[[ 7  8  9]
 [10 11 12]]


In [40]:
# Finds max values across different depths.
# [[ max(1,7)   max(2,8)   max(3,9) ]  
#  [ max(4,10)  max(5,11)  max(6,12)]]

In [41]:
# 2️⃣ Find Maximum Along axis=1 (Row-Wise)
print(arr.max(axis=1))
# Finds max values across rows within each depth.

[[ 4  5  6]
 [10 11 12]]


In [43]:
# 3️⃣ Find Maximum Along axis=2 (Column-Wise)
print(arr.max(axis=2))
# Finds max values across columns within each row and depth.

[[ 3  6]
 [ 9 12]]


In [44]:
# 3.Using keepdims=True
print(arr.max(keepdims=True))

[[[12]]]


In [47]:
# 4: Using initial Parameter
print(arr.max(initial=11))
# Since 12 is the largest value in the array, and initial=11, it returns 12.

12


In [53]:
#  5: Using where Parameter
mask = arr%2==0
print(arr.max(where=mask,initial=0))
# finds the max among even numbers (2, 4, 6, ..., 12).

12


# 10.min() Method

In [54]:
# The min() method in NumPy finds the minimum value along a specified axis in a 3D array.

# 🔹 Syntax:
# numpy.min(arr, axis=None, out=None, keepdims=False, initial=None, where=True)

# 🔹 Parameters:
# axis	Specifies the axis along which to find the minimum. Default is None (finds min of all elements).
# out	An optional output array to store the result. Must have the same shape as expected output.
# keepdims	If True, retains reduced dimensions with size 1 instead of collapsing them.
# initial	The starting value for comparison. If specified, min will compare against this value.
# where	A boolean mask specifying which elements to consider in the minimum calculation

In [55]:
arr = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [56]:
# 1: Find the Minimum in a 3D Array
print(arr.min())
# Finds the lowest value across the entire array (1).

1


In [57]:
#  2: Find Minimum Along Different Axes
# 1️⃣ Find Minimum Along axis=0 (Depth-Wise)

print(arr.min(axis=0))
# Finds min values across different depths.

[[1 2 3]
 [4 5 6]]


In [58]:
# 2️⃣ Find Minimum Along axis=1 (Row-Wise)
print(arr.min(axis=1))
# Finds min values across rows within each depth.

[[1 2 3]
 [7 8 9]]


In [59]:
# 3️⃣ Find Minimum Along axis=2 (Column-Wise)
print(arr.min(axis=2))

[[ 1  4]
 [ 7 10]]


# 11. argmax() Method

In [60]:
# The argmax() method in NumPy returns the index of the maximum value along a specified axis in a 3D array.

# 🔹 Syntax:
# numpy.argmax(arr, axis=None, out=None, keepdims=False)

# 🔹 Parameters:
# Parameter	Description
# axis	Specifies the axis along which to find the index of the maximum value. Default is None (finds index in the flattened array).
# out	An optional output array to store the result. Must have the same shape as expected output.
# keepdims	If True, retains reduced dimensions with size 1 instead of collapsing them.

In [62]:
arr = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [65]:
# 1: Find the Index of Maximum in a 3D Array
print(arr.argmax())
# Finds the index of the max value (18) in the flattened array (axis=None).

11


In [67]:
# 2: Find Maximum Indices Along Different Axes
# 1️⃣ Find Index of Maximum Along axis=0 (Depth-Wise)
print(arr.argmax(axis=0))

# Explanation:

# Finds the index where the max value occurs across different depths.

# [[ index of max(1,7)   index of max(2,8)   index of max(3,9) ]  
#  [ index of max(4,10)  index of max(5,11)  index of max(6,12) ]]

# Since 7, 8, 9 (in depth index 2) are the largest, the index 1 is returned.
# Similarly, for 10, 11, 12, the index 1 is returned.

[[1 1 1]
 [1 1 1]]


In [68]:
# 2️⃣ Find Index of Maximum Along axis=1 (Row-Wise)
print(arr.argmax(axis=1))
# Finds index where the max value occurs across rows within each depth.

[[1 1 1]
 [1 1 1]]


In [70]:
# 3️⃣ Find Index of Maximum Along axis=2 (Column-Wise)
print(arr.argmax(axis=2))

[[2 2]
 [2 2]]


# 12.mean() Method

In [71]:
# The mean() method in NumPy calculates the average (arithmetic mean) of elements in a 3D array, either for the entire array or along a specified axis.

# 🔹 Syntax:
# numpy.mean(arr, axis=None, dtype=None, out=None, keepdims=False, where=True)

# 🔹 Parameters:
# axis	Specifies the axis along which to compute the mean. Default is None (computes mean of all elements).
# dtype	Specifies the data type of the result. Default is inferred from the input.
# out	An optional array to store the result. Must match expected output shape.
# keepdims	If True, retains reduced dimensions with size 1 instead of collapsing them.
# where	A Boolean mask that specifies which elements to include in the calculation.

In [75]:
arr = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]],
    [[13,14,15],[16,17,18]]
])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [76]:
# 1: Compute Mean of the Entire 3D Array
print(arr.mean())

9.5


In [77]:
# 2: Compute Mean Along Different Axes
# 1️⃣ Compute Mean Along axis=0 (Depth-Wise)
print(arr.mean(axis=0))

# Explanation:
# Computes mean across different depths.

# Formula for each element:
# [[ (1+7+13)/3   (2+8+14)/3   (3+9+15)/3 ]  
#  [ (4+10+16)/3  (5+11+17)/3  (6+12+18)/3 ]]
# The result is a 2D array of shape (2,3).

[[ 7.  8.  9.]
 [10. 11. 12.]]


In [79]:
# 2️⃣ Compute Mean Along axis=1 (Row-Wise)
print(arr.mean(axis=1))

# Explanation:
# Computes mean along rows for each depth.

# Formula:

# [[ (1+4)/2   (2+5)/2   (3+6)/2 ]  
#  [ (7+10)/2  (8+11)/2  (9+12)/2 ]  
#  [ (13+16)/2 (14+17)/2 (15+18)/2 ]]
# The result is a 2D array of shape (3,3).

[[ 2.5  3.5  4.5]
 [ 8.5  9.5 10.5]
 [14.5 15.5 16.5]]


In [81]:
# 3️⃣ Compute Mean Along axis=2 (Column-Wise)
print(arr.mean(axis=2))

# Explanation:
# Computes mean across columns for each row and depth.

# Formula:
# [[ (1+2+3)/3   (4+5+6)/3 ]  
#  [ (7+8+9)/3   (10+11+12)/3 ]  
#  [ (13+14+15)/3 (16+17+18)/3 ]]
# The result is a 2D array of shape (3,2).

[[ 2.  5.]
 [ 8. 11.]
 [14. 17.]]


# 13.var() Method

In [83]:
# The var() method in NumPy calculates the variance of elements in a 3D array, either for the entire array or along a specified axis.

# 🔹 Syntax
# numpy.var(arr, axis=None, dtype=None, out=None, ddof=0, keepdims=False, where=True)

# 🔹 Parameters
# axis	Specifies the axis along which to compute variance. Default is None (computes for all elements).
# dtype	Specifies the data type of the result. Default is inferred from input.
# out	An optional array to store the result. Must match expected output shape.
# keepdims	If True, retains reduced dimensions with size 1 instead of collapsing them.
# where	A Boolean mask that specifies which elements to include in the calculation.

In [84]:
arr = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]],
    [[13,14,15],[16,17,18]]
])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [85]:
# 1: Compute Variance of the Entire 3D Array
print(arr.var())

26.916666666666668


In [86]:
# 2.Compute Variance Along Different Axes
# 1️⃣ Compute Variance Along axis=0 (Depth-Wise)
print(arr.var(axis=0))



[[24. 24. 24.]
 [24. 24. 24.]]


In [87]:
# 2️⃣ Compute Variance Along axis=1 (Row-Wise)
print(arr.var(axis=1))

[[2.25 2.25 2.25]
 [2.25 2.25 2.25]
 [2.25 2.25 2.25]]


In [88]:
# 3️⃣ Compute Variance Along axis=2 (Column-Wise)
print(arr.var(axis=2))

[[0.66666667 0.66666667]
 [0.66666667 0.66666667]
 [0.66666667 0.66666667]]


# 14.std() Method


In [89]:
# The std() method in NumPy calculates the standard deviation of elements in a 3D array.

# 🔹 Definition of Standard Deviation
# The standard deviation measures the spread of data from the mean. It is the square root of variance:
    
# 🔹 Syntax
# numpy.std(arr, axis=None, dtype=None, out=None, ddof=0, keepdims=False, where=True)

# 🔹 Parameters
# axis	Specifies the axis along which to compute the standard deviation. Default is None (computes for all elements).
# dtype	Specifies the data type of the result (e.g., np.float32).
# out	An optional array to store the result. Must match the expected output shape.
# ddof	Delta Degrees of Freedom. Default is 0 (N), but setting ddof=1 computes the sample standard deviation (N-1).
# keepdims	If True, retains reduced dimensions with size 1 instead of collapsing them.
# where	A Boolean mask that specifies which elements to include in the calculation.

In [90]:
print(arr.std())

5.188127472091127


# 15.sort() Method

In [1]:
# The numpy.sort() function is used to sort elements along a specified axis of a 3D array.

# 🔹 Syntax
# numpy.sort(a, axis=-1, kind=None, order=None)

# 🔹 Parameters
# a	The input 3D NumPy array to be sorted.
# axis	Axis along which to sort elements. Default is -1 (last axis).
# kind	Sorting algorithm to use. Options: ‘quicksort’, ‘mergesort’, ‘heapsort’, ‘stable’. Default: ‘quicksort’.
# order	Used when sorting structured arrays. (Not relevant for 3D arrays).

# 🔹 Return Type
# Returns a new NumPy array with elements sorted along the specified axis.

In [4]:
arr = np.array([
    [[9, 2, 7], [3, 8, 5]],
    [[1, 6, 4], [7, 2, 0]]
])
print(arr)

[[[9 2 7]
  [3 8 5]]

 [[1 6 4]
  [7 2 0]]]


In [9]:
print("Original Array")
print(arr)
print()
sort_arr = np.sort(arr)
print("Sorted Array")
print(sort_arr)

# Sorts each row within depth layers along the last axis (axis=-1).

Original Array
[[[9 2 7]
  [3 8 5]]

 [[1 6 4]
  [7 2 0]]]

Sorted Array
[[[2 7 9]
  [3 5 8]]

 [[1 4 6]
  [0 2 7]]]


In [14]:
# 2️⃣ Sorting Along axis=0 (Depth Axis)
print("Original Array")
print(arr)
print()
print("Sorted Array")
sort_arr = np.sort(arr,axis=0)
print(sort_arr)
# Sorts elements across different depth layers for each row-column index.

Original Array
[[[9 2 7]
  [3 8 5]]

 [[1 6 4]
  [7 2 0]]]

[[[1 2 4]
  [3 2 0]]

 [[9 6 7]
  [7 8 5]]]


In [15]:
# 3️⃣ Sorting Along axis=1 (Row Axis)
print("Original Array")
print(arr)
print()
print("Sorted Array")
sort_arr = np.sort(arr,axis=1)
print(sort_arr)
# Sorts each row within the depth layers.

Original Array
[[[9 2 7]
  [3 8 5]]

 [[1 6 4]
  [7 2 0]]]

Sorted Array
[[[3 2 5]
  [9 8 7]]

 [[1 2 0]
  [7 6 4]]]


In [17]:
print("Original Array")
print(arr)
print()
print("Sorted Array")
sort_arr = np.sort(arr,axis=2)
print(sort_arr)
# sorting across columns-rows within each depth.

Original Array
[[[9 2 7]
  [3 8 5]]

 [[1 6 4]
  [7 2 0]]]

Sorted Array
[[[2 7 9]
  [3 5 8]]

 [[1 4 6]
  [0 2 7]]]


# 16.concatenate() Method

In [18]:
# The numpy.concatenate() function joins multiple NumPy arrays along a specified axis.

# 🔹 Syntax
# numpy.concatenate((arr1, arr2, ...), axis=0, out=None, dtype=None, casting="same_kind")

# 🔹 Parameters
# (arr1, arr2, ...)	A tuple or list of NumPy arrays to be concatenated. Arrays must have the same shape except for the specified axis.
# axis	Axis along which to concatenate. Default is 0.
# out	Optional output array to store the result. Must have the correct shape.
# dtype	Specifies the data type of the resulting array (optional).
# casting	Defines how data type conversion should happen. Default is "same_kind".

# 🔹 Return Type
# Returns a new NumPy array formed by concatenating the input arrays.

In [19]:
arr1 = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

arr2 = np.array([
    [[9,10],[11,12]],
    [[13,14],[15,16]]
])
print(arr1)
print()
print(arr2)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

[[[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]


In [22]:
# 1️⃣ Concatenating Along axis=0 (Depth Axis)
concatenated_arr = np.concatenate((arr1, arr2), axis=0)
print(concatenated_arr)
# The arrays are stacked depth-wise (axis=0), increasing the number of layers.

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]


In [23]:
# 2️⃣ Concatenating Along axis=1 (Row Axis)
concatenated_arr = np.concatenate((arr1, arr2), axis=1)
print(concatenated_arr)
# The number of rows increases, but depth remains the same.

[[[ 1  2]
  [ 3  4]
  [ 9 10]
  [11 12]]

 [[ 5  6]
  [ 7  8]
  [13 14]
  [15 16]]]


In [25]:
# 3️⃣ Concatenating Along axis=2 (Column Axis)
concatenated_arr = np.concatenate((arr1, arr2), axis=2)
print(concatenated_arr)
# concatencation cross column-row within different depth.

[[[ 1  2  9 10]
  [ 3  4 11 12]]

 [[ 5  6 13 14]
  [ 7  8 15 16]]]


# 17.unique() Method 

In [26]:
# The numpy.unique() function finds the unique elements of an array and provides additional options for counting, sorting, and returning indices.

# 🔹 Syntax
# numpy.unique(arr, return_index=False, return_inverse=False, return_counts=False, axis=None)

# 🔹 Parameters
# arr	The input array (3D array in this case).
# return_index	If True, returns the indices of the first occurrences of the unique values.
# return_inverse	If True, returns indices to reconstruct the input array from unique values.
# return_counts	If True, returns the count of each unique element.
# axis	Specifies the axis along which to find unique elements. If None (default), it flattens the array first.

# 🔹 Return Type
# Returns an array of unique elements.
# Optionally returns:
# Indices of first occurrences
# Indices for reconstructing the input
# Counts of occurrences

In [27]:
arr = np.array([
    [[1,2],[1,2]],
    [[3,4],[5,6]],
    [[10,11],[12,13]]
])
print(arr)

[[[ 1  2]
  [ 1  2]]

 [[ 3  4]
  [ 5  6]]

 [[10 11]
  [12 13]]]


In [29]:
# 1️⃣Finding Unique Elements in a 3D Array
unique_arr = np.unique(arr)
print(unique_arr)

[ 1  2  3  4  5  6 10 11 12 13]


In [31]:
# 2️⃣ Returning Unique Elements with Index Positions
unique_arr = np.unique(arr,return_index=True)
print(unique_arr)

(array([ 1,  2,  3,  4,  5,  6, 10, 11, 12, 13]), array([ 0,  1,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int64))


In [33]:
# 3️⃣ Counting Occurrences of Each Unique Value
unique_arr = np.unique(arr,return_counts=True)
print(unique_arr)

(array([ 1,  2,  3,  4,  5,  6, 10, 11, 12, 13]), array([2, 2, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64))


# 18.clip() Method 

In [34]:
# The numpy.clip() method is used to limit the values in an array to a specified range. Any values lower than the minimum are set to the minimum, and any values higher than the maximum are set to the maximum.

# 🔹 Syntax
# numpy.clip(arr, a_min, a_max, out=None)

# 🔹 Parameters
# arr	The input 3D array whose values will be clipped.
# a_min	The lower bound. Values below this are set to a_min. If None, no lower limit.
# a_max	The upper bound. Values above this are set to a_max. If None, no upper limit.
# out	Optional output array of the same shape as arr. Stores the result instead of creating a new array.

# 🔹 Return Type
# A new array with values clipped between a_min and a_max, unless out is specified, in which case the modification happens in-place.

In [35]:
arr = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]],
    [[13,14,15],[16,17,18]]
])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [38]:
new_arr = np.clip(arr,a_min=5,a_max=9)
print(new_arr)

[[[5 5 5]
  [5 5 6]]

 [[7 8 9]
  [9 9 9]]

 [[9 9 9]
  [9 9 9]]]


# 19.where() Method

In [39]:
# The numpy.where() function is used for conditional selection and modification of array elements. 
# It returns indices or replaces elements based on conditions.

# 🔹 Syntax
# numpy.where(condition, [x, y])

# 🔹 Parameters
# condition	A boolean condition applied to the array.
# x	Optional. Values to use where condition is True.
# y	Optional. Values to use where condition is False.

# 🔹 Return Type
# If only condition is given, it returns indices of True values.
# If x and y are given, it returns an array with values replaced based on the condition

In [40]:
arr = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]],
    [[13,14,15],[16,17,18]]
])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [43]:
# 1️⃣ Finding Indices Where Condition is True

new_arr = np.where(arr>10)
print(new_arr)

# Returns the indices (depth, row, column) where arr > 10.

(array([1, 1, 2, 2, 2, 2, 2, 2], dtype=int64), array([1, 1, 0, 0, 0, 1, 1, 1], dtype=int64), array([1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))


In [45]:
# 2️⃣ Replacing Values Based on Condition
new_arr = np.where(arr>10,0,1)
print(new_arr)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 0 0]]

 [[0 0 0]
  [0 0 0]]]


# 20.any() Method

In [46]:
# The numpy.any() function checks if at least one element in a 3D array is True (or nonzero) along a specified axis.

# 🔹 Syntax
# numpy.any(arr, axis=None, out=None, keepdims=False, where=True)

# 🔹 Parameters
# arr	Input 3D array (can be boolean or numeric).
# axis	Axis along which to check for True values. Default is None (checks all elements).
# out	Optional output array to store the result.
# keepdims	If True, retains the reduced dimension with size 1.
# where	Boolean mask to specify elements to consider.

In [56]:
arr = np.array([
    [[1,0,1],[0,0,1]],
    [[1,1,1],[1,0,0]],
])
print(arr)

[[[1 0 1]
  [0 0 1]]

 [[1 1 1]
  [1 0 0]]]


In [58]:
# 1: Check If Any Element is Non-Zero
ans = arr.any()
print(ans)

True


In [57]:
# 2: Check Along axis=0 (Depth-Wise)
ans = arr.any(axis=0)
print(ans)

# Checks across depths (different layers).
# A position gets True if at least one element in that position across all depths is nonzero.

[[ True  True  True]
 [ True False  True]]


In [60]:
# 3: Check Along axis=1 (Row-Wise)
ans = arr.any(axis=1)
print(ans)
# Row-column wise within same depth.

[[ True False  True]
 [ True  True  True]]


In [63]:
#  4: Check Along axis=2 (Column-Wise)
ans = arr.any(axis=2)
print(ans)
# Column row wise within same depth.

[[ True  True]
 [ True  True]]
